#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
//
// Embed WGSL shader files as TypeScript string constants. Runs as part of
// the viewer's build/test pipeline so the WGSL files remain the canonical
// shader source while `tsc` (which doesn't grok `.wgsl`) can still produce
// a self-contained ESM module.
//
// Reads all .wgsl files under packages/viewer/src/webgpu/
// Writes:
//   packages/viewer/src/webgpu/shaders.generated.ts

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const wgpu = join(root, 'src', 'webgpu');

const decode = readFileSync(join(wgpu, 'decode.wgsl'), 'utf8');
const radix = readFileSync(join(wgpu, 'radix_sort.wgsl'), 'utf8');
const fused = readFileSync(join(wgpu, 'cs_project_gather.wgsl'), 'utf8');
const scan = readFileSync(join(wgpu, 'scan_multiblock.wgsl'), 'utf8');
const histo = readFileSync(join(wgpu, 'histogram_subgroup.wgsl'), 'utf8');
const cull = readFileSync(join(wgpu, 'cs_cull.wgsl'), 'utf8');
const wsrClear = readFileSync(join(wgpu, 'cs_wsr_clear.wgsl'), 'utf8');
const wsrAccum = readFileSync(join(wgpu, 'cs_wsr_accumulate.wgsl'), 'utf8');
const wsrResolve = readFileSync(join(wgpu, 'cs_wsr_resolve.wgsl'), 'utf8');
const tileBin = readFileSync(join(wgpu, 'cs_tile_bin.wgsl'), 'utf8');
const wsrTileAccum = readFileSync(join(wgpu, 'cs_wsr_tile_accumulate.wgsl'), 'utf8');

const escape = (s) => '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';

const out = `// SPDX-License-Identifier: Apache-2.0
// AUTO-GENERATED by scripts/embed-wgsl.mjs — DO NOT EDIT.

export const DECODE_WGSL: string = ${escape(decode)};

export const RADIX_SORT_WGSL: string = ${escape(radix)};

export const PROJECT_GATHER_WGSL: string = ${escape(fused)};

export const SCAN_MULTIBLOCK_WGSL: string = ${escape(scan)};

export const HISTOGRAM_SUBGROUP_WGSL: string = ${escape(histo)};

export const CULL_WGSL: string = ${escape(cull)};

export const WSR_CLEAR_WGSL: string = ${escape(wsrClear)};

export const WSR_ACCUMULATE_WGSL: string = ${escape(wsrAccum)};

export const WSR_RESOLVE_WGSL: string = ${escape(wsrResolve)};

export const TILE_BIN_WGSL: string = ${escape(tileBin)};

export const WSR_TILE_ACCUMULATE_WGSL: string = ${escape(wsrTileAccum)};
`;

writeFileSync(join(wgpu, 'shaders.generated.ts'), out);
console.error('embed-wgsl: wrote shaders.generated.ts');
