#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
//
// Embed WGSL shader files as TypeScript string constants. Runs as part of
// the viewer's build/test pipeline so the WGSL files remain the canonical
// shader source while `tsc` (which doesn't grok `.wgsl`) can still produce
// a self-contained ESM module.
//
// Reads:
//   packages/viewer/src/webgpu/decode.wgsl
//   packages/viewer/src/webgpu/radix_sort.wgsl
//   packages/viewer/src/webgpu/scan_multiblock.wgsl
//   packages/viewer/src/webgpu/histogram_subgroup.wgsl
// Writes:
//   packages/viewer/src/webgpu/shaders.generated.ts

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const wgpu = join(root, 'src', 'webgpu');

const decode = readFileSync(join(wgpu, 'decode.wgsl'), 'utf8');
const radix = readFileSync(join(wgpu, 'radix_sort.wgsl'), 'utf8');
const scanMultiblock = readFileSync(join(wgpu, 'scan_multiblock.wgsl'), 'utf8');
const histogramSubgroup = readFileSync(join(wgpu, 'histogram_subgroup.wgsl'), 'utf8');

const escape = (s) => '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';

const out = `// SPDX-License-Identifier: Apache-2.0
// AUTO-GENERATED by scripts/embed-wgsl.mjs - DO NOT EDIT.
// Source files: src/webgpu/decode.wgsl, src/webgpu/radix_sort.wgsl,
//               src/webgpu/scan_multiblock.wgsl,
//               src/webgpu/histogram_subgroup.wgsl.

export const DECODE_WGSL: string = ${escape(decode)};

export const RADIX_SORT_WGSL: string = ${escape(radix)};

export const SCAN_MULTIBLOCK_WGSL: string = ${escape(scanMultiblock)};

export const HISTOGRAM_SUBGROUP_WGSL: string = ${escape(histogramSubgroup)};
`;

writeFileSync(join(wgpu, 'shaders.generated.ts'), out);
console.error('embed-wgsl: wrote shaders.generated.ts');
