// swift-tools-version:5.9
//
// SplatforgeViewer — iOS / iPadOS / macOS Swift Package.
//
// The package vendors the Rust `splatforge-viewer-mobile` staticlib as an
// XCFramework (built by `scripts/build-xcframework.sh`) and wraps it in a
// SwiftUI `SplatforgeViewer` that renders splat assets with Metal.
//
// Until the XCFramework is built locally this manifest declares the targets
// using plain C/Swift sources so `swift build` on macOS still type-checks.

import PackageDescription

let package = Package(
    name: "SplatforgeViewer",
    platforms: [
        .iOS(.v15),
        .macOS(.v13)
    ],
    products: [
        .library(
            name: "SplatforgeViewer",
            targets: ["SplatforgeViewer"]
        )
    ],
    targets: [
        // Resource-only Swift target that owns the MSL compute kernels.
        // Both the main viewer target AND the kernel-parity tests depend on
        // this so the shaders live in exactly one place on disk.
        .target(
            name: "SplatforgeShaders",
            path: "Sources/SplatforgeShaders",
            resources: [
                .process("Shaders")
            ]
        ),
        // Pure-C shim that exposes the Rust C ABI to Swift. The header is
        // auto-generated by `scripts/regen-headers.sh` (cbindgen).
        .target(
            name: "SplatforgeViewerC",
            path: "Sources/SplatforgeViewerC",
            publicHeadersPath: "include"
        ),
        .target(
            name: "SplatforgeViewer",
            dependencies: ["SplatforgeViewerC", "SplatforgeShaders"],
            path: "Sources/SplatforgeViewer"
        ),
        // Kernel-parity tests. Each test compiles one of the .metal files at
        // runtime against the local Metal device, runs it over a fixture
        // input, and asserts the output matches a Swift CPU oracle (which
        // mirrors the Rust core's reference path in `core/src/sort.rs` etc).
        //
        // The test target deliberately does NOT depend on `SplatforgeViewer`
        // — that target links against the Rust `splatforge-viewer-mobile`
        // staticlib which is not vendored in this PR (XCFramework build is a
        // separate local step). Instead the tests treat the .metal files as
        // their own bundle resource so they run with `swift test` on any host
        // with Xcode + Metal Toolchain installed.
        //
        // On CI runners without a GPU, individual tests `XCTSkip` rather than
        // fail so the rest of `swift test` stays green.
        .testTarget(
            name: "SplatforgeViewerTests",
            dependencies: ["SplatforgeShaders"],
            path: "Tests/SplatforgeViewerTests"
        )
    ]
)
