// swift-tools-version:5.9
//
// CatetusViewer — iOS / iPadOS / macOS Swift Package.
//
// The package vendors the Rust `catetus-viewer-mobile` staticlib as an
// XCFramework (built by `scripts/build-xcframework.sh`) and wraps it in a
// SwiftUI `CatetusViewer` that renders splat assets with Metal.
//
// The binary target `CatetusViewerCore` carries the Rust staticlib for
// iOS device, iOS simulator (arm64+x86_64 fat), and macOS (arm64+x86_64 fat).
// The XCFramework also ships the `catetus_viewer_mobile.h` header so Swift
// can import the C ABI directly without a separate shim target.

import PackageDescription

let package = Package(
    name: "CatetusViewer",
    platforms: [
        .iOS(.v15),
        .macOS(.v13)
    ],
    products: [
        .library(
            name: "CatetusViewer",
            targets: ["CatetusViewer"]
        )
    ],
    targets: [
        // Resource-only Swift target that owns the MSL compute kernels.
        // Both the main viewer target AND the kernel-parity tests depend on
        // this so the shaders live in exactly one place on disk.
        .target(
            name: "CatetusShaders",
            path: "Sources/CatetusShaders",
            resources: [
                .process("Shaders")
            ]
        ),
        // Rust staticlib + C header, shipped as an XCFramework with iOS,
        // iOS-sim, and macOS slices. Build with `scripts/build-xcframework.sh`.
        //
        // The XCFramework exports a Clang module named `CatetusViewerC`
        // (the Headers/ dir contains a module.modulemap auto-generated by
        // `xcodebuild -create-xcframework`). Swift imports the C ABI via
        // `import CatetusViewerC`, which resolves to this binary target.
        .binaryTarget(
            name: "CatetusViewerC",
            path: "CatetusViewerCore.xcframework"
        ),
        .target(
            name: "CatetusViewer",
            dependencies: ["CatetusViewerC", "CatetusShaders"],
            path: "Sources/CatetusViewer"
        ),
        // Kernel-parity tests. Each test compiles one of the .metal files at
        // runtime against the local Metal device, runs it over a fixture
        // input, and asserts the output matches a Swift CPU oracle (which
        // mirrors the Rust core's reference path in `core/src/sort.rs` etc).
        //
        // The test target deliberately does NOT depend on `CatetusViewer`
        // — that target links against the Rust `catetus-viewer-mobile`
        // staticlib which is not vendored in this PR (XCFramework build is a
        // separate local step). Instead the tests treat the .metal files as
        // their own bundle resource so they run with `swift test` on any host
        // with Xcode + Metal Toolchain installed.
        //
        // On CI runners without a GPU, individual tests `XCTSkip` rather than
        // fail so the rest of `swift test` stays green.
        .testTarget(
            name: "CatetusViewerTests",
            dependencies: ["CatetusShaders", "CatetusViewerC"],
            path: "Tests/CatetusViewerTests"
        )
    ]
)
