// SPDX-License-Identifier: Apache-2.0
// AUTO-GENERATED by scripts/embed-wgsl.mjs — DO NOT EDIT.

export const DECODE_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// WebGPU compute decode shader for SplatForge SoA splat chunks.
//
// Input  (storage, read):  packed bytes of a single chunk laid out as
//                          POSITION u16x3 normalized  | min, max from uniform
//                          ROTATION f32x4
//                          SCALE    u8x3  normalized  | min, max from uniform
//                          OPACITY  u8    normalized  | min=0, max=1
//                          COLOR_DC u8x3  normalized  | min=0, max=1
//
// Output (storage, write): array<DecodedSplat> — one record per splat in the
//                          canonical decoded form fed to the project pass.
//
// One workgroup-thread = one splat. Workgroup size 256 chosen to comfortably
// fit on every WebGPU implementation (Apple Silicon, Adreno, Mali) without
// hitting the 16384-byte workgroup shared-memory cap; we don't use shared
// memory in this pass.
//
// The math mirrors \`decodeAttribute\` in renderer/base.ts so the GPU and CPU
// paths produce bit-identical results modulo float-precision noise.

struct DecodedSplat {
  // vec4 packing keeps storage-buffer alignment at 16B. The shader emits
  //   pos.xyz   = world position
  //   pos.w     = opacity (so we save 12 bytes vs a separate vec4).
  //   scale.xyz = anisotropic scale
  //   scale.w   = reserved (0)
  //   rot.xyzw  = quaternion (x,y,z,w)
  //   color.rgb = DC SH coefficient as linear RGB
  //   color.a   = reserved (1)
  pos:   vec4<f32>,
  scale: vec4<f32>,
  rot:   vec4<f32>,
  color: vec4<f32>,
};

struct AttributeSlice {
  byte_offset: u32,
  // Each element is f32 even for ints — we burn 16B per slice but get
  // straight-line WGSL with no scalar-load conversions.
  comp_type:   u32, // 5121 u8, 5123 u16, 5126 f32
  normalized:  u32, // 0/1
  _pad:        u32,
  // Per-component dequant bounds. comp 0..3.
  vmin: vec4<f32>,
  vmax: vec4<f32>,
};

struct DecodeUniforms {
  splat_count: u32,
  _pad0: u32,
  _pad1: u32,
  _pad2: u32,
  positions: AttributeSlice,
  rotations: AttributeSlice,
  scales:    AttributeSlice,
  opacities: AttributeSlice,
  color_dc:  AttributeSlice,
};

@group(0) @binding(0) var<storage, read>       src_bytes : array<u32>;
@group(0) @binding(1) var<storage, read_write> dst_splats : array<DecodedSplat>;
@group(0) @binding(2) var<uniform>             u : DecodeUniforms;

// Load an unsigned byte from a u32 storage buffer at absolute byte offset \`b\`.
fn load_u8(b: u32) -> u32 {
  let word = src_bytes[b >> 2u];
  let sh   = (b & 3u) * 8u;
  return (word >> sh) & 0xffu;
}

// Load an unsigned 16-bit little-endian short.
fn load_u16(b: u32) -> u32 {
  // Two byte fetches always work, including across u32 boundaries. The two
  // are folded by the driver when aligned.
  let lo = load_u8(b);
  let hi = load_u8(b + 1u);
  return lo | (hi << 8u);
}

// Load a little-endian f32 by reading 4 contiguous bytes. WebGPU storage
// buffers are byte-addressable but not byte-typed; we reassemble.
fn load_f32(b: u32) -> f32 {
  let b0 = load_u8(b);
  let b1 = load_u8(b + 1u);
  let b2 = load_u8(b + 2u);
  let b3 = load_u8(b + 3u);
  return bitcast<f32>(b0 | (b1 << 8u) | (b2 << 16u) | (b3 << 24u));
}

// Decode one scalar attribute component at byte offset \`b\` according to
// the slice's comp_type / normalized / min / max.
fn decode_component(slice: AttributeSlice, b: u32, k: u32) -> f32 {
  if (slice.comp_type == 5126u) {
    return load_f32(b);
  }
  if (slice.comp_type == 5123u) {
    let raw = f32(load_u16(b));
    if (slice.normalized == 1u) {
      let lo = slice.vmin[k];
      let hi = slice.vmax[k];
      return lo + (raw / 65535.0) * (hi - lo);
    }
    return raw;
  }
  // default: 5121 u8
  let raw = f32(load_u8(b));
  if (slice.normalized == 1u) {
    let lo = slice.vmin[k];
    let hi = slice.vmax[k];
    return lo + (raw / 255.0) * (hi - lo);
  }
  return raw;
}

fn comp_stride(slice: AttributeSlice) -> u32 {
  if (slice.comp_type == 5126u) { return 4u; }
  if (slice.comp_type == 5123u) { return 2u; }
  return 1u;
}

@compute @workgroup_size(256)
fn cs_decode(@builtin(global_invocation_id) gid : vec3<u32>) {
  let i = gid.x;
  if (i >= u.splat_count) { return; }

  // POSITION (vec3)
  let p_stride = comp_stride(u.positions);
  let p_base = u.positions.byte_offset + i * 3u * p_stride;
  let px = decode_component(u.positions, p_base + 0u * p_stride, 0u);
  let py = decode_component(u.positions, p_base + 1u * p_stride, 1u);
  let pz = decode_component(u.positions, p_base + 2u * p_stride, 2u);

  // ROTATION (vec4) — always f32 on the wire today.
  let r_stride = comp_stride(u.rotations);
  let r_base = u.rotations.byte_offset + i * 4u * r_stride;
  let rx = decode_component(u.rotations, r_base + 0u * r_stride, 0u);
  let ry = decode_component(u.rotations, r_base + 1u * r_stride, 1u);
  let rz = decode_component(u.rotations, r_base + 2u * r_stride, 2u);
  let rw = decode_component(u.rotations, r_base + 3u * r_stride, 3u);

  // SCALE (vec3)
  let s_stride = comp_stride(u.scales);
  let s_base = u.scales.byte_offset + i * 3u * s_stride;
  let sx = decode_component(u.scales, s_base + 0u * s_stride, 0u);
  let sy = decode_component(u.scales, s_base + 1u * s_stride, 1u);
  let sz = decode_component(u.scales, s_base + 2u * s_stride, 2u);

  // OPACITY (scalar)
  let o_stride = comp_stride(u.opacities);
  let opacity = decode_component(u.opacities, u.opacities.byte_offset + i * o_stride, 0u);

  // COLOR_DC (vec3)
  let c_stride = comp_stride(u.color_dc);
  let c_base = u.color_dc.byte_offset + i * 3u * c_stride;
  let cr = decode_component(u.color_dc, c_base + 0u * c_stride, 0u);
  let cg = decode_component(u.color_dc, c_base + 1u * c_stride, 1u);
  let cb = decode_component(u.color_dc, c_base + 2u * c_stride, 2u);

  var out: DecodedSplat;
  out.pos   = vec4<f32>(px, py, pz, opacity);
  out.scale = vec4<f32>(sx, sy, sz, 0.0);
  out.rot   = vec4<f32>(rx, ry, rz, rw);
  out.color = vec4<f32>(cr, cg, cb, 1.0);
  dst_splats[i] = out;
}

// ---------------------------------------------------------------------------
// Project pass: canonical splats + camera → per-instance render attributes
// (clipPos, 2D covariance, premultiplied color) + sortable depth keys.
// ---------------------------------------------------------------------------

struct ProjectUniforms {
  view: mat4x4<f32>,
  view_proj: mat4x4<f32>,
  viewport: vec2<f32>,
  focal:    vec2<f32>,
  splat_count: u32,
  _pad: u32,
  _pad2: vec2<u32>,
};

// Per-instance vertex-buffer record (must match FLOATS_PER_INSTANCE=12).
struct Instance {
  clip_pos: vec4<f32>,
  cov:      vec4<f32>,
  color:    vec4<f32>,
};

@group(0) @binding(0) var<storage, read>       p_splats   : array<DecodedSplat>;
@group(0) @binding(1) var<storage, read_write> p_inst     : array<Instance>;
@group(0) @binding(2) var<storage, read_write> p_keys     : array<u32>;
@group(0) @binding(3) var<storage, read_write> p_indices  : array<u32>;
@group(0) @binding(4) var<uniform>             pu : ProjectUniforms;

// Build the upper-triangular 3D covariance Σ = R · diag(s²) · Rᵀ.
// Returns the six unique entries as (σxx, σxy, σxz, σyy, σyz, σzz).
fn cov3d(scale: vec3<f32>, q: vec4<f32>) -> array<f32, 6> {
  // Normalize the quaternion defensively (mirrors quatToMat3).
  let n = max(length(q), 1e-8);
  let qn = q / n;
  let x = qn.x; let y = qn.y; let z = qn.z; let w = qn.w;
  let xx = x*x; let yy = y*y; let zz = z*z;
  let xy = x*y; let xz = x*z; let yz = y*z;
  let wx = w*x; let wy = w*y; let wz = w*z;
  // Column-major rotation matrix.
  let r00 = 1.0 - 2.0*(yy + zz);
  let r10 = 2.0*(xy + wz);
  let r20 = 2.0*(xz - wy);
  let r01 = 2.0*(xy - wz);
  let r11 = 1.0 - 2.0*(xx + zz);
  let r21 = 2.0*(yz + wx);
  let r02 = 2.0*(xz + wy);
  let r12 = 2.0*(yz - wx);
  let r22 = 1.0 - 2.0*(xx + yy);
  let sx = scale.x; let sy = scale.y; let sz = scale.z;
  let m00 = r00*sx; let m10 = r10*sx; let m20 = r20*sx;
  let m01 = r01*sy; let m11 = r11*sy; let m21 = r21*sy;
  let m02 = r02*sz; let m12 = r12*sz; let m22 = r22*sz;
  return array<f32, 6>(
    m00*m00 + m01*m01 + m02*m02,
    m00*m10 + m01*m11 + m02*m12,
    m00*m20 + m01*m21 + m02*m22,
    m10*m10 + m11*m11 + m12*m12,
    m10*m20 + m11*m21 + m12*m22,
    m20*m20 + m21*m21 + m22*m22,
  );
}

@compute @workgroup_size(256)
fn cs_project(@builtin(global_invocation_id) gid : vec3<u32>) {
  let i = gid.x;
  if (i >= pu.splat_count) { return; }

  let s = p_splats[i];
  let pos = s.pos.xyz;
  let opacity = s.pos.w;

  // Clip-space.
  let clip = pu.view_proj * vec4<f32>(pos, 1.0);
  let invW = select(1.0, 1.0 / clip.w, abs(clip.w) > 1e-12);
  let ndc = vec3<f32>(clip.x * invW, clip.y * invW, clip.z * invW);

  // View-space depth: column-major mat4x4 indexed as m[col][row]; row 2 of the
  // view matrix dotted with (pos, 1) is \`-z\` of the view-space point.
  let vz = pu.view[0][2] * pos.x + pu.view[1][2] * pos.y + pu.view[2][2] * pos.z + pu.view[3][2];
  let depth = -vz;
  let behind = depth <= 0.0;

  // Reconstruct 3D covariance, project into 2D screen covariance.
  let V = cov3d(s.scale.xyz, s.rot);
  // Symmetric Σ entries:
  //   V[0]=σxx, V[1]=σxy, V[2]=σxz, V[3]=σyy, V[4]=σyz, V[5]=σzz.
  // World→view rotation rows.
  let w0 = vec3<f32>(pu.view[0][0], pu.view[1][0], pu.view[2][0]);
  let w1 = vec3<f32>(pu.view[0][1], pu.view[1][1], pu.view[2][1]);
  let a0 = vec3<f32>(
    w0.x * V[0] + w0.y * V[1] + w0.z * V[2],
    w0.x * V[1] + w0.y * V[3] + w0.z * V[4],
    w0.x * V[2] + w0.y * V[4] + w0.z * V[5],
  );
  let a1 = vec3<f32>(
    w1.x * V[0] + w1.y * V[1] + w1.z * V[2],
    w1.x * V[1] + w1.y * V[3] + w1.z * V[4],
    w1.x * V[2] + w1.y * V[4] + w1.z * V[5],
  );
  let vxx = dot(a0, w0);
  let vxy = dot(a0, w1);
  let vyy = dot(a1, w1);

  let z = max(abs(depth), 1e-4);
  let jx = pu.focal.x / z;
  let jy = pu.focal.y / z;
  let reg = 0.3; // SF_EWA_DILATION
  let c00 = jx * jx * vxx + reg;
  let c01 = jx * jy * vxy;
  let c11 = jy * jy * vyy + reg;

  // 3σ radius (px) from largest eigenvalue of the 2x2.
  let half_trace = 0.5 * (c00 + c11);
  let det = max(c00 * c11 - c01 * c01, 0.0);
  let term = sqrt(max(half_trace * half_trace - det, 0.0));
  let lambda_max = half_trace + term;
  var radius = 3.0 * sqrt(max(lambda_max, 0.0));
  if (behind) { radius = 0.0; }

  var inst: Instance;
  let zc = clamp(ndc.z, 0.0, 1.0);
  if (behind) {
    inst.clip_pos = vec4<f32>(2.0, 2.0, 1.0, 1.0); // off-screen; radius=0 also kills it
    inst.cov      = vec4<f32>(1.0, 0.0, 1.0, 0.0);
  } else {
    inst.clip_pos = vec4<f32>(ndc.xy, zc, clip.w);
    inst.cov      = vec4<f32>(c00, c01, c11, radius);
  }
  inst.color = vec4<f32>(s.color.rgb, opacity);
  p_inst[i] = inst;

  // Sort key: bigger view-space depth = drawn first (back-to-front). We bit-
  // pack a u32 from the float. To get correct ascending order over both
  // signs of f32 IEEE-754 reinterpret + a fix-up flip is required, but here
  // we sort positive depths only — behind-camera splats get depth=0 and are
  // suppressed by radius=0 anyway.
  let dpos = max(depth, 0.0);
  // We want back-to-front => largest depth FIRST. Radix sort below sorts
  // ascending, so we invert: key = 0xFFFFFFFF - bitcast(d) gives descending
  // semantics. NaN-safe because dpos is clamped.
  let kd = bitcast<u32>(dpos);
  p_keys[i] = 0xffffffffu - kd;
  p_indices[i] = i;
}
`;

export const RADIX_SORT_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// WebGPU radix sort over u32 keys, carrying a u32 payload (the splat index).
//
// Algorithm: classic 8-bit (256-bin) LSD radix sort. Each 32-bit key is sorted
// in 4 sequential passes. Each pass consists of three kernels:
//
//   1. cs_histogram  — per-workgroup local histogram, written out to
//                      \`histograms[bin * num_wgs + wgid]\`. WG_SIZE = 256, so
//                      each thread owns exactly one bin during init/writeout.
//   2. cs_scan       — exclusive prefix sum over the entire histogram array
//                      (length numWorkgroups * 256). At 10 M splats that's
//                      ~10 M entries — far beyond the single-WG scan's
//                      working set, so the multi-block chained scan in
//                      \`scan_multiblock.wgsl\` is the only viable path here.
//   3. cs_scatter    — read scanned offsets, scatter each (key, index) pair
//                      into its bucket position.
//
// 8-bit (256-bin) vs the previous 4-bit (16-bin) layout:
//   - Halves the number of passes (8 -> 4). At the per-pass dispatch
//     granularity for 10 M splats, that's a near-2x reduction in radix-sort
//     compute work (modulo the larger scan-input size).
//   - Grows the per-pass histogram array 16x (numWgs * 16 -> numWgs * 256),
//     i.e. ~625 K -> ~10 M u32s per pass at 10 M splats. The multi-block
//     scan in \`scan_multiblock.wgsl\` (already chained, parallelized across
//     all available workgroups) handles this size; the legacy single-WG
//     \`cs_scan\` would not.
//   - Workgroup-shared histogram (\`wg_hist[RADIX]\`) grows 16x to 1 KiB,
//     well under the 16 KiB workgroup-shared cap on every WebGPU device.
//   - \`wg_offsets[RADIX]\` likewise grows to 1 KiB.
//
// We deliberately avoid storage-buffer atomics: each workgroup writes its own
// histogram slot, the scan runs across many workgroups (see
// \`scan_multiblock.wgsl\`) using only workgroup-shared atomics in the
// histogram kernel, and the scatter uses a per-workgroup local prefix scan
// to compute intra-workgroup destination offsets without atomicAdd on
// storage. Atomics on storage buffers are still optional in WebGPU 1.0 and
// not on the mandatory feature set.
//
// Inspired by:
//   - Wyman, "wgsl-radix-sort" (github.com/cwyman/wgsl-radix-sort) - overall
//     three-pass split radix structure.
//   - Merrill & Grimshaw 2010, "High Performance and Scalable Radix Sorting".
//   - antimatter15 / splatviz GPU sort prototypes (multi-pass LSD on u32).

const WG_SIZE : u32 = 256u;
const RADIX   : u32 = 256u;      // 8-bit radix -> 256 bins per pass.
const RADIX_MASK : u32 = 0xffu;  // RADIX - 1
const PASSES  : u32 = 4u;        // 32 bits / 8 bits

struct Uniforms {
  count: u32,
  bit_shift: u32,    // 0, 8, 16, 24
  num_wgs: u32,      // ceil(count / WG_SIZE)
  _pad: u32,
};

@group(0) @binding(0) var<storage, read>       keys_in    : array<u32>;
@group(0) @binding(1) var<storage, read>       values_in  : array<u32>;
@group(0) @binding(2) var<storage, read_write> keys_out   : array<u32>;
@group(0) @binding(3) var<storage, read_write> values_out : array<u32>;
@group(0) @binding(4) var<storage, read_write> histograms : array<u32>;
@group(0) @binding(5) var<uniform>             u : Uniforms;

// Workgroup-shared per-bin counters. With 8-bit radix, RADIX == WG_SIZE so
// every thread initializes / reads exactly one bin during init/writeout —
// no \`if (lid.x < RADIX)\` guard needed.
var<workgroup> wg_hist : array<atomic<u32>, RADIX>;
// Workgroup-shared offsets table used in the scatter pass.
var<workgroup> wg_offsets : array<u32, RADIX>;
// Workgroup-shared scan scratch (single-workgroup scan over per-thread totals).
var<workgroup> scan_scratch : array<u32, WG_SIZE>;

// ---------------------------------------------------------------------------
// Pass 1: histogram. One workgroup of 256 threads handles 256 keys; each
// thread atomically increments the bucket for its key. The atomics here are
// *workgroup*-scoped — WebGPU mandates \`atomic<u32>\` in \`var<workgroup>\`.
// (Storage-buffer atomics are NOT used anywhere.)
//
// With RADIX == WG_SIZE the init / writeout loop collapses to one statement
// per thread.
// ---------------------------------------------------------------------------
@compute @workgroup_size(WG_SIZE)
fn cs_histogram(
  @builtin(global_invocation_id)  gid : vec3<u32>,
  @builtin(local_invocation_id)   lid : vec3<u32>,
  @builtin(workgroup_id)          wgid : vec3<u32>,
) {
  atomicStore(&wg_hist[lid.x], 0u);
  workgroupBarrier();

  let i = gid.x;
  if (i < u.count) {
    let k = keys_in[i];
    let bin = (k >> u.bit_shift) & RADIX_MASK;
    atomicAdd(&wg_hist[bin], 1u);
  }
  workgroupBarrier();

  // Each thread writes one bin to the global histogram table at slot
  // [bin * num_wgs + wgid]. This bin-major layout means the global exclusive
  // scan naturally places all of bin 0's workgroups first, then bin 1's,
  // etc. — i.e. ascending sort order without an extra grouping pass after
  // the scan.
  let h = atomicLoad(&wg_hist[lid.x]);
  histograms[lid.x * u.num_wgs + wgid.x] = h;
}

// ---------------------------------------------------------------------------
// Pass 2 (legacy single-WG scan): exclusive prefix-sum over the entire
// histogram array. This shader runs as a single workgroup (256 threads) and
// strides through the entire \`histograms\` array. Retained for
// non-multi-block-scan callers (e.g. older test setups); at 8-bit radix the
// histogram is ~10 M u32s for 10 M splats, which is far too large for a
// single workgroup to scan in any reasonable time. Real callers MUST use
// \`scan_multiblock.wgsl\` — the orchestration in \`radix_sort.ts\` enables it
// by default and treats the multi-block scan as a hard requirement when
// RADIX == 256.
// ---------------------------------------------------------------------------
@compute @workgroup_size(WG_SIZE)
fn cs_scan(@builtin(local_invocation_id) lid : vec3<u32>) {
  let total = u.num_wgs * RADIX;
  // Step 1: each thread sums its strided slice.
  var tsum: u32 = 0u;
  var idx: u32 = lid.x;
  loop {
    if (idx >= total) { break; }
    tsum = tsum + histograms[idx];
    idx = idx + WG_SIZE;
  }
  scan_scratch[lid.x] = tsum;
  workgroupBarrier();

  // Step 2: in-shared exclusive scan over WG_SIZE entries. Hillis-Steele.
  for (var offset: u32 = 1u; offset < WG_SIZE; offset = offset << 1u) {
    var v: u32 = 0u;
    if (lid.x >= offset) {
      v = scan_scratch[lid.x - offset];
    }
    workgroupBarrier();
    scan_scratch[lid.x] = scan_scratch[lid.x] + v;
    workgroupBarrier();
  }
  // Convert inclusive -> exclusive scan.
  let prefix_total = scan_scratch[lid.x];
  let my_block_exclusive = prefix_total - tsum;
  workgroupBarrier();

  // Step 3: walk strided slice again, writing exclusive prefix.
  var running: u32 = my_block_exclusive;
  var idx2: u32 = lid.x;
  loop {
    if (idx2 >= total) { break; }
    let v = histograms[idx2];
    histograms[idx2] = running;
    running = running + v;
    idx2 = idx2 + WG_SIZE;
  }
}

// ---------------------------------------------------------------------------
// Pass 3: scatter. Each workgroup recomputes its local histogram (cheaper
// than persisting per-element bin assignments to a side buffer), then derives
// each element's destination index as:
//
//   dst[i] = histograms[bin_of(i) * num_wgs + wgid]  (global exclusive prefix)
//          + local_position_of(i, bin_of(i))
//
// We compute \`local_position_of\` by re-scanning bins inside the workgroup:
// thread 0 of each bin atomically adds, then we use the returned old value
// as the local rank. Order within a bin is the natural intra-workgroup
// dispatch order — which is deterministic given a fixed global-id pattern.
// ---------------------------------------------------------------------------
@compute @workgroup_size(WG_SIZE)
fn cs_scatter(
  @builtin(global_invocation_id) gid : vec3<u32>,
  @builtin(local_invocation_id)  lid : vec3<u32>,
  @builtin(workgroup_id)         wgid: vec3<u32>,
) {
  // Init per-bin local counters to 0. Read the global exclusive offset for
  // this (bin, workgroup) pair from the bin-major scanned histogram.
  // RADIX == WG_SIZE so every thread does exactly one init/load.
  atomicStore(&wg_hist[lid.x], 0u);
  wg_offsets[lid.x] = histograms[lid.x * u.num_wgs + wgid.x];
  workgroupBarrier();

  let i = gid.x;
  var bin: u32 = 0u;
  var key: u32 = 0u;
  var val: u32 = 0u;
  var local_rank: u32 = 0u;
  var live: bool = false;
  if (i < u.count) {
    key = keys_in[i];
    val = values_in[i];
    bin = (key >> u.bit_shift) & RADIX_MASK;
    // atomicAdd returns the old value -> that's the rank of this element
    // within its bin for this workgroup.
    local_rank = atomicAdd(&wg_hist[bin], 1u);
    live = true;
  }
  workgroupBarrier();

  if (live) {
    let dst = wg_offsets[bin] + local_rank;
    keys_out[dst]   = key;
    values_out[dst] = val;
  }
}
`;

export const PROJECT_GATHER_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// Fused project + gather compute shaders.
//
// The non-fused pipeline (decode.wgsl) writes per-instance vertex records
// into an *unsorted* scratch buffer (\`instUnsorted\`, 64 B/splat = 640 MB at
// 10 M splats), then a separate \`cs_gather\` kernel reorders those records
// into the final vertex buffer using the radix-sort output indices. That
// scratch read+write is pure DRAM bandwidth — it dominates at high splat
// counts (~30 % of the frame at 10 M, per bench/4090-clean-single-tenant).
//
// The fused path replaces that with:
//
//   1. cs_keygen          — 1 thread per splat. Reads canonical splat
//                           position only, computes the back-to-front depth
//                           sort key, writes (keys[i], indices[i]).
//                           No projection work, no covariance, no instance
//                           record. Cheap.
//   2. radix sort (existing) — sorts indices by depth.
//   3. cs_project_gather  — 1 thread per *output* slot. Thread \`i\` reads
//                           \`splat_idx = indices[i]\`, projects the splat
//                           at that index, and writes the resulting
//                           Instance record directly to \`instanceBuffer[i]\`.
//
// Net effect at 10 M splats:
//   - \`instUnsorted\` (640 MB) is never allocated, written, or read.
//   - Projection math runs ONCE (in cs_project_gather), not twice.
//   - Saves one full 640 MB write (cs_project → instUnsorted) and one full
//     640 MB read (cs_gather ← instUnsorted) per frame.
//
// Math invariant: cs_project_gather produces bit-identical Instance records
// to the non-fused (cs_project + cs_gather) path. We achieve this by
// keeping the projection math in this file *byte-for-byte identical* to the
// math in decode.wgsl::cs_project (same operation ordering, same constants).
// The fused-vs-separate parity test in __tests__/webgpu/fused_project_gather
// pins this invariant.

struct DecodedSplat {
  pos:   vec4<f32>,
  scale: vec4<f32>,
  rot:   vec4<f32>,
  color: vec4<f32>,
};

struct Instance {
  clip_pos: vec4<f32>,
  cov:      vec4<f32>,
  color:    vec4<f32>,
};

struct ProjectUniforms {
  view: mat4x4<f32>,
  view_proj: mat4x4<f32>,
  viewport: vec2<f32>,
  focal:    vec2<f32>,
  splat_count: u32,
  _pad: u32,
  _pad2: vec2<u32>,
};

// ---------------------------------------------------------------------------
// cs_keygen — depth-only pre-pass.
// ---------------------------------------------------------------------------

@group(0) @binding(0) var<storage, read>       k_splats  : array<DecodedSplat>;
@group(0) @binding(1) var<storage, read_write> k_keys    : array<u32>;
@group(0) @binding(2) var<storage, read_write> k_indices : array<u32>;
@group(0) @binding(3) var<uniform>             ku        : ProjectUniforms;

@compute @workgroup_size(256)
fn cs_keygen(@builtin(global_invocation_id) gid : vec3<u32>) {
  let i = gid.x;
  if (i >= ku.splat_count) { return; }
  let s = k_splats[i];
  let pos = s.pos.xyz;
  // View-space depth: column-major mat4 indexed as m[col][row]. Row 2 of view
  // dotted with (pos,1) is -z of the view-space point. MUST match cs_project.
  let vz = ku.view[0][2] * pos.x + ku.view[1][2] * pos.y + ku.view[2][2] * pos.z + ku.view[3][2];
  let depth = -vz;
  let dpos = max(depth, 0.0);
  let kd = bitcast<u32>(dpos);
  k_keys[i] = 0xffffffffu - kd;
  k_indices[i] = i;
}

// ---------------------------------------------------------------------------
// cs_project_gather — full projection in sorted order, direct to vertex buf.
//
// IMPORTANT: the body of this function is the *exact* same math as cs_project
// in decode.wgsl. Any change here must be mirrored there or the parity test
// will fail.
// ---------------------------------------------------------------------------

@group(0) @binding(0) var<storage, read>       g_splats   : array<DecodedSplat>;
@group(0) @binding(1) var<storage, read>       g_indices  : array<u32>;
@group(0) @binding(2) var<storage, read_write> g_inst_out : array<Instance>;
@group(0) @binding(3) var<uniform>             gu         : ProjectUniforms;

// Build the upper-triangular 3D covariance Σ = R · diag(s²) · Rᵀ.
// Returns (σxx, σxy, σxz, σyy, σyz, σzz). Mirrors cov3d() in decode.wgsl.
fn cov3d_fg(scale: vec3<f32>, q: vec4<f32>) -> array<f32, 6> {
  let n = max(length(q), 1e-8);
  let qn = q / n;
  let x = qn.x; let y = qn.y; let z = qn.z; let w = qn.w;
  let xx = x*x; let yy = y*y; let zz = z*z;
  let xy = x*y; let xz = x*z; let yz = y*z;
  let wx = w*x; let wy = w*y; let wz = w*z;
  let r00 = 1.0 - 2.0*(yy + zz);
  let r10 = 2.0*(xy + wz);
  let r20 = 2.0*(xz - wy);
  let r01 = 2.0*(xy - wz);
  let r11 = 1.0 - 2.0*(xx + zz);
  let r21 = 2.0*(yz + wx);
  let r02 = 2.0*(xz + wy);
  let r12 = 2.0*(yz - wx);
  let r22 = 1.0 - 2.0*(xx + yy);
  let sx = scale.x; let sy = scale.y; let sz = scale.z;
  let m00 = r00*sx; let m10 = r10*sx; let m20 = r20*sx;
  let m01 = r01*sy; let m11 = r11*sy; let m21 = r21*sy;
  let m02 = r02*sz; let m12 = r12*sz; let m22 = r22*sz;
  return array<f32, 6>(
    m00*m00 + m01*m01 + m02*m02,
    m00*m10 + m01*m11 + m02*m12,
    m00*m20 + m01*m21 + m02*m22,
    m10*m10 + m11*m11 + m12*m12,
    m10*m20 + m11*m21 + m12*m22,
    m20*m20 + m21*m21 + m22*m22,
  );
}

@compute @workgroup_size(256)
fn cs_project_gather(@builtin(global_invocation_id) gid : vec3<u32>) {
  let i = gid.x;
  if (i >= gu.splat_count) { return; }

  // Indirection: thread \`i\` writes the i-th sorted slot; we read the splat
  // index from the radix-sort output, then project that splat.
  let splat_idx = g_indices[i];
  let s = g_splats[splat_idx];
  let pos = s.pos.xyz;
  let opacity = s.pos.w;

  // Clip-space. (Identical to cs_project in decode.wgsl.)
  let clip = gu.view_proj * vec4<f32>(pos, 1.0);
  let invW = select(1.0, 1.0 / clip.w, abs(clip.w) > 1e-12);
  let ndc = vec3<f32>(clip.x * invW, clip.y * invW, clip.z * invW);

  let vz = gu.view[0][2] * pos.x + gu.view[1][2] * pos.y + gu.view[2][2] * pos.z + gu.view[3][2];
  let depth = -vz;
  let behind = depth <= 0.0;

  let V = cov3d_fg(s.scale.xyz, s.rot);
  let w0 = vec3<f32>(gu.view[0][0], gu.view[1][0], gu.view[2][0]);
  let w1 = vec3<f32>(gu.view[0][1], gu.view[1][1], gu.view[2][1]);
  let a0 = vec3<f32>(
    w0.x * V[0] + w0.y * V[1] + w0.z * V[2],
    w0.x * V[1] + w0.y * V[3] + w0.z * V[4],
    w0.x * V[2] + w0.y * V[4] + w0.z * V[5],
  );
  let a1 = vec3<f32>(
    w1.x * V[0] + w1.y * V[1] + w1.z * V[2],
    w1.x * V[1] + w1.y * V[3] + w1.z * V[4],
    w1.x * V[2] + w1.y * V[4] + w1.z * V[5],
  );
  let vxx = dot(a0, w0);
  let vxy = dot(a0, w1);
  let vyy = dot(a1, w1);

  let z = max(abs(depth), 1e-4);
  let jx = gu.focal.x / z;
  let jy = gu.focal.y / z;
  let reg = 0.3; // SF_EWA_DILATION
  let c00 = jx * jx * vxx + reg;
  let c01 = jx * jy * vxy;
  let c11 = jy * jy * vyy + reg;

  let half_trace = 0.5 * (c00 + c11);
  let det = max(c00 * c11 - c01 * c01, 0.0);
  let term = sqrt(max(half_trace * half_trace - det, 0.0));
  let lambda_max = half_trace + term;
  var radius = 3.0 * sqrt(max(lambda_max, 0.0));
  if (behind) { radius = 0.0; }

  var inst: Instance;
  let zc = clamp(ndc.z, 0.0, 1.0);
  if (behind) {
    inst.clip_pos = vec4<f32>(2.0, 2.0, 1.0, 1.0);
    inst.cov      = vec4<f32>(1.0, 0.0, 1.0, 0.0);
  } else {
    inst.clip_pos = vec4<f32>(ndc.xy, zc, clip.w);
    inst.cov      = vec4<f32>(c00, c01, c11, radius);
  }
  inst.color = vec4<f32>(s.color.rgb, opacity);
  g_inst_out[i] = inst;
}
`;

export const SCAN_MULTIBLOCK_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// Multi-block exclusive prefix-sum (3-kernel chained scan).
//
// Replaces the single-workgroup \`cs_scan\` step inside the radix sort. The
// original implementation had a single workgroup of 256 threads stride
// through the entire histogram array (\`num_wgs * RADIX\` elements). For
// 10 M splats that's ~625 K elements scanned by 256 threads, eight times
// per sort — the dominant cost in the sort.
//
// This file implements the classic chained scan from Merrill & Grimshaw 2010
// using zero storage-buffer atomics (we don't have them mandatory in
// WebGPU 1.0). Three kernels per scan:
//
//   1. cs_scan_per_wg          — each workgroup of \`WG_SIZE\` threads does an
//                                exclusive scan over its tile, writes the
//                                scan back in-place, and writes the tile
//                                total to \`block_sums[wgid]\`.
//   2. cs_scan_block_sums      — a single workgroup does an exclusive scan
//                                over the \`block_sums\` array. For up to
//                                \`2 * WG_SIZE * WG_SIZE\` = 131 072 tiles
//                                (which is 33 M-element tiles' worth of
//                                block sums; far more than we ever need
//                                — 10 M splats yield ~2 442 tiles) the
//                                single-WG scan with serial striding is
//                                trivial and not the bottleneck.
//   3. cs_scan_add_block_sums  — each workgroup adds its scanned
//                                \`block_sums[wgid]\` to every element in its
//                                tile, producing the final global exclusive
//                                prefix.
//
// We intentionally keep the bind-group layout identical to the existing
// radix-sort layout (binding 4 = histograms / data, binding 5 = uniforms),
// but add a sixth binding for \`block_sums\`. The radix-sort orchestration
// rebinds for these kernels because the meaning of bindings 0..3 differs.
//
// Inspired by:
//   - Merrill & Grimshaw 2010, "Parallel Scan for Stream Architectures".
//   - Harris et al., "Parallel Prefix Sum (Scan) with CUDA", GPU Gems 3.
//   - Wyman, "wgsl-radix-sort", for the WGSL idiom (workgroup-shared
//     Hillis-Steele).

const WG_SIZE : u32 = 256u;

struct ScanUniforms {
  total:        u32,   // total elements to scan == num_wgs_radix * RADIX
  num_scan_wgs: u32,   // ceil(total / WG_SIZE)
  _pad0:        u32,
  _pad1:        u32,
};

@group(0) @binding(0) var<storage, read_write> data       : array<u32>;
@group(0) @binding(1) var<storage, read_write> block_sums : array<u32>;
@group(0) @binding(2) var<uniform>             us         : ScanUniforms;

// Workgroup-shared scan scratch.
var<workgroup> ss_scratch : array<u32, WG_SIZE>;

// ---------------------------------------------------------------------------
// Phase A: per-workgroup exclusive scan over a \`WG_SIZE\` tile.
//
// Each workgroup loads its tile into shared memory, performs a Hillis-Steele
// scan (inclusive → exclusive), writes the exclusive prefix back to \`data\`,
// and stores the tile total in \`block_sums[wgid]\`.
// ---------------------------------------------------------------------------
@compute @workgroup_size(WG_SIZE)
fn cs_scan_per_wg(
  @builtin(global_invocation_id) gid  : vec3<u32>,
  @builtin(local_invocation_id)  lid  : vec3<u32>,
  @builtin(workgroup_id)         wgid : vec3<u32>,
) {
  let i = gid.x;
  var v: u32 = 0u;
  if (i < us.total) {
    v = data[i];
  }
  ss_scratch[lid.x] = v;
  workgroupBarrier();

  // Hillis-Steele inclusive scan over WG_SIZE entries.
  for (var offset: u32 = 1u; offset < WG_SIZE; offset = offset << 1u) {
    var add: u32 = 0u;
    if (lid.x >= offset) {
      add = ss_scratch[lid.x - offset];
    }
    workgroupBarrier();
    ss_scratch[lid.x] = ss_scratch[lid.x] + add;
    workgroupBarrier();
  }

  // Inclusive[lid] - original[lid] = exclusive[lid].
  let inclusive = ss_scratch[lid.x];
  let exclusive = inclusive - v;
  if (i < us.total) {
    data[i] = exclusive;
  }

  // Last live thread in this tile writes the block total.
  // For a fully-populated tile this is lid.x == WG_SIZE - 1.
  // For the tail tile (i >= us.total beyond some point) we still want the
  // last-loaded element's inclusive prefix, which is the tile's total over
  // the valid prefix only (v was zero for OOB lanes).
  if (lid.x == WG_SIZE - 1u) {
    block_sums[wgid.x] = inclusive;
  }
}

// ---------------------------------------------------------------------------
// Phase B: single-workgroup exclusive scan over \`block_sums\`.
//
// \`num_scan_wgs\` is small (≤ a few thousand for 10 M splats per pass), so a
// single workgroup of WG_SIZE threads striding through the array is fine.
// This kernel mirrors the original \`cs_scan\` body but operates on
// \`block_sums\` instead of \`histograms\`.
// ---------------------------------------------------------------------------
@compute @workgroup_size(WG_SIZE)
fn cs_scan_block_sums(@builtin(local_invocation_id) lid : vec3<u32>) {
  let total = us.num_scan_wgs;
  // Step 1: each thread sums its strided slice.
  var tsum: u32 = 0u;
  var idx: u32 = lid.x;
  loop {
    if (idx >= total) { break; }
    tsum = tsum + block_sums[idx];
    idx = idx + WG_SIZE;
  }
  ss_scratch[lid.x] = tsum;
  workgroupBarrier();

  // Step 2: shared exclusive scan over WG_SIZE per-thread totals.
  for (var offset: u32 = 1u; offset < WG_SIZE; offset = offset << 1u) {
    var v: u32 = 0u;
    if (lid.x >= offset) {
      v = ss_scratch[lid.x - offset];
    }
    workgroupBarrier();
    ss_scratch[lid.x] = ss_scratch[lid.x] + v;
    workgroupBarrier();
  }
  let prefix_total = ss_scratch[lid.x];
  let my_block_exclusive = prefix_total - tsum;
  workgroupBarrier();

  // Step 3: re-walk slice, writing the exclusive prefix back.
  var running: u32 = my_block_exclusive;
  var idx2: u32 = lid.x;
  loop {
    if (idx2 >= total) { break; }
    let v = block_sums[idx2];
    block_sums[idx2] = running;
    running = running + v;
    idx2 = idx2 + WG_SIZE;
  }
}

// ---------------------------------------------------------------------------
// Phase C: each workgroup adds its exclusive \`block_sums[wgid]\` to every
// element of its tile, producing the global exclusive prefix sum.
// ---------------------------------------------------------------------------
@compute @workgroup_size(WG_SIZE)
fn cs_scan_add_block_sums(
  @builtin(global_invocation_id) gid  : vec3<u32>,
  @builtin(workgroup_id)         wgid : vec3<u32>,
) {
  let i = gid.x;
  if (i >= us.total) { return; }
  let bias = block_sums[wgid.x];
  data[i] = data[i] + bias;
}
`;

export const HISTOGRAM_SUBGROUP_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// Subgroup-aware histogram kernel for the radix sort.
//
// Functionally equivalent to \`cs_histogram\` in \`radix_sort.wgsl\`, but uses
// WebGPU 1.1 subgroup ops to cut the workgroup-shared atomic-add traffic
// when several lanes in the same subgroup hit the same bin (a common case
// once the keys are partially sorted - i.e. all passes after the first).
//
// Strategy (small, conservative - one workgroup-shared atomic per
// (subgroup, unique-bin) pair instead of per-lane):
//
//   - Each lane computes its own \`bin\` (or RADIX = "dead lane").
//   - If every live lane in the subgroup has the same bin (cheap
//     \`subgroupBroadcastFirst\` + \`subgroupAll\` check), the elected lane
//     issues a single \`atomicAdd(&wg_hist[bin], subgroup_size)\`.
//   - Otherwise, each lane falls back to its own atomicAdd. Atomics on
//     \`var<workgroup>\` are mandatory in WebGPU 1.0 and are typically backed
//     by LDS atomics on real GPUs, so the fallback is still fine.
//
// Why this pattern and not per-bin ballot+popcount: with RADIX == 256
// (8-bit), a ballot-per-bin loop is 256 iterations per lane, which dwarfs
// the gain. The "all-lanes-agree" shortcut is O(1) per lane and is the
// dominant case for partially-sorted keys (passes 2..4 of a 4-pass sort).
//
// Bind-group layout is *identical* to \`radix_sort.wgsl\`s \`cs_histogram\`
// (same group/binding indices, same struct ordering). The orchestration in
// \`radix_sort.ts\` swaps between the two kernels at compile time based on
// \`adapter.features.has('subgroups')\`.

enable subgroups;

const WG_SIZE : u32 = 256u;
const RADIX   : u32 = 256u;
const RADIX_MASK : u32 = 0xffu;

struct Uniforms {
  count: u32,
  bit_shift: u32,
  num_wgs: u32,
  _pad: u32,
};

@group(0) @binding(0) var<storage, read>       keys_in    : array<u32>;
@group(0) @binding(1) var<storage, read>       values_in  : array<u32>;
@group(0) @binding(2) var<storage, read_write> keys_out   : array<u32>;
@group(0) @binding(3) var<storage, read_write> values_out : array<u32>;
@group(0) @binding(4) var<storage, read_write> histograms : array<u32>;
@group(0) @binding(5) var<uniform>             u : Uniforms;

var<workgroup> wg_hist : array<atomic<u32>, RADIX>;

@compute @workgroup_size(WG_SIZE)
fn cs_histogram_subgroup(
  @builtin(global_invocation_id)   gid : vec3<u32>,
  @builtin(local_invocation_id)    lid : vec3<u32>,
  @builtin(workgroup_id)           wgid : vec3<u32>,
  @builtin(subgroup_size)          sg_size : u32,
  @builtin(subgroup_invocation_id) sg_lane : u32,
) {
  atomicStore(&wg_hist[lid.x], 0u);
  workgroupBarrier();

  let i = gid.x;
  let live = i < u.count;
  // Dead lanes use a sentinel bin (RADIX) so the "all agree" check below
  // never coalesces a dead lane with a live one. RADIX is out of bounds
  // for wg_hist, so the sentinel never reaches atomicAdd.
  var bin: u32 = RADIX;
  if (live) {
    let k = keys_in[i];
    bin = (k >> u.bit_shift) & RADIX_MASK;
  }

  // Cheap subgroup-wide coalesce: if every lane in this subgroup has the
  // same bin (and is live), one atomicAdd per subgroup instead of \`sg_size\`.
  let leader_bin = subgroupBroadcastFirst(bin);
  let all_same = subgroupAll(bin == leader_bin);
  if (all_same && leader_bin != RADIX) {
    // Whole subgroup hits the same live bin. One atomicAdd of sg_size.
    if (sg_lane == 0u) {
      atomicAdd(&wg_hist[leader_bin], sg_size);
    }
  } else {
    // Mixed bins (or partially-dead subgroup at the tail). Each live lane
    // does its own atomicAdd; dead lanes (bin == RADIX) do nothing.
    if (live) {
      atomicAdd(&wg_hist[bin], 1u);
    }
  }
  workgroupBarrier();

  let h = atomicLoad(&wg_hist[lid.x]);
  histograms[lid.x * u.num_wgs + wgid.x] = h;
}
`;

export const CULL_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// Opacity-radius pre-sort cull.
//
// Drops splats that cannot contribute a visible pixel before they enter the
// project / sort / gather pipeline. Implemented as three compute kernels:
//
//   1. cs_cull         - 1 thread / splat. Computes the 2D screen covariance
//                        and writes alive_flag[i] = 1 if the splat survives,
//                        0 otherwise. The predicate is:
//                          alpha >= tau    (opacity above the floor)        AND
//                          depth > 0       (in front of the camera)         AND
//                          r_max >= 0.5 px (the iso-opacity threshold
//                                           ellipse exceeds one pixel)
//                        with r_max = sigma * sqrt(2 * ln(alpha / tau)).
//                        The flag is written to TWO buffers:
//                          flag_buffer[i]   = the original 0/1 (read by
//                                             cs_compact to gate the write).
//                          prefix_buffer[i] = same 0/1, consumed in-place by
//                                             the scan_multiblock kernels
//                                             which turn it into an exclusive
//                                             prefix sum.
//
//   2. cs_compact      - 1 thread / splat. Reads flag_buffer[i] (alive?) and
//                        prefix_buffer[i] (scatter target). If alive, writes
//                        compact_indices[prefix_buffer[i]] = i.
//
//   3. cs_project_cmpct - 1 thread / survivor. Reads compact_indices[i] ->
//                         splat index si, re-runs the projection on
//                         splats[si], writes inst[i] / keys[i] / values[i].
//                         keys[i]   = depth-bits packed for descending sort.
//                         values[i] = i (the compact-position index - so the
//                         gather stage finds the per-survivor Instance via
//                         dst[k] = src[sorted_values[k]]).
//
// Determinism: no storage-buffer atomics. The prefix sum used by cs_compact
// is provided by the scan_multiblock kernels which are atomic-free.
//
// Math invariant: cs_project_cmpct produces bit-identical Instance records
// to cs_project for the surviving subset; the projection math is copied
// verbatim and the only difference is the index indirection.

struct DecodedSplat {
  pos:   vec4<f32>,
  scale: vec4<f32>,
  rot:   vec4<f32>,
  color: vec4<f32>,
};

struct Instance {
  clip_pos: vec4<f32>,
  cov:      vec4<f32>,
  color:    vec4<f32>,
};

struct CullUniforms {
  view:        mat4x4<f32>,
  view_proj:   mat4x4<f32>,
  viewport:    vec2<f32>,
  focal:       vec2<f32>,
  splat_count: u32,
  tau:         f32,
  _pad:        vec2<u32>,
};

// =============================================================================
// cs_cull bindings:
//   0 (read)        : splats[]
//   1 (read_write)  : flag_buffer[]    (final 0/1 flags, read by cs_compact)
//   2 (read_write)  : prefix_buffer[]  (also 0/1; turned into exclusive prefix
//                                       in place by the scan_multiblock pass)
//   3 (uniform)     : CullUniforms
// =============================================================================
@group(0) @binding(0) var<storage, read>       cu_splats : array<DecodedSplat>;
@group(0) @binding(1) var<storage, read_write> cu_flag   : array<u32>;
@group(0) @binding(2) var<storage, read_write> cu_prefix : array<u32>;
@group(0) @binding(3) var<uniform>             cu_u      : CullUniforms;

fn cov3d_cull(scale: vec3<f32>, q: vec4<f32>) -> array<f32, 6> {
  let n = max(length(q), 1e-8);
  let qn = q / n;
  let x = qn.x; let y = qn.y; let z = qn.z; let w = qn.w;
  let xx = x*x; let yy = y*y; let zz = z*z;
  let xy = x*y; let xz = x*z; let yz = y*z;
  let wx = w*x; let wy = w*y; let wz = w*z;
  let r00 = 1.0 - 2.0*(yy + zz);
  let r10 = 2.0*(xy + wz);
  let r20 = 2.0*(xz - wy);
  let r01 = 2.0*(xy - wz);
  let r11 = 1.0 - 2.0*(xx + zz);
  let r21 = 2.0*(yz + wx);
  let r02 = 2.0*(xz + wy);
  let r12 = 2.0*(yz - wx);
  let r22 = 1.0 - 2.0*(xx + yy);
  let sx = scale.x; let sy = scale.y; let sz = scale.z;
  let m00 = r00*sx; let m10 = r10*sx; let m20 = r20*sx;
  let m01 = r01*sy; let m11 = r11*sy; let m21 = r21*sy;
  let m02 = r02*sz; let m12 = r12*sz; let m22 = r22*sz;
  return array<f32, 6>(
    m00*m00 + m01*m01 + m02*m02,
    m00*m10 + m01*m11 + m02*m12,
    m00*m20 + m01*m21 + m02*m22,
    m10*m10 + m11*m11 + m12*m12,
    m10*m20 + m11*m21 + m12*m22,
    m20*m20 + m21*m21 + m22*m22,
  );
}

@compute @workgroup_size(256)
fn cs_cull(@builtin(global_invocation_id) gid : vec3<u32>) {
  let i = gid.x;
  if (i >= cu_u.splat_count) { return; }

  let s = cu_splats[i];
  let pos = s.pos.xyz;
  let alpha = s.pos.w;

  var alive: u32 = 0u;

  // Cheap reject 1: opacity below the perceptual floor.
  if (alpha >= cu_u.tau) {
    // View-space depth.
    let vz = cu_u.view[0][2] * pos.x + cu_u.view[1][2] * pos.y + cu_u.view[2][2] * pos.z + cu_u.view[3][2];
    let depth = -vz;
    if (depth > 0.0) {
      // Project to 2D covariance.
      let V = cov3d_cull(s.scale.xyz, s.rot);
      let w0 = vec3<f32>(cu_u.view[0][0], cu_u.view[1][0], cu_u.view[2][0]);
      let w1 = vec3<f32>(cu_u.view[0][1], cu_u.view[1][1], cu_u.view[2][1]);
      let a0 = vec3<f32>(
        w0.x * V[0] + w0.y * V[1] + w0.z * V[2],
        w0.x * V[1] + w0.y * V[3] + w0.z * V[4],
        w0.x * V[2] + w0.y * V[4] + w0.z * V[5],
      );
      let a1 = vec3<f32>(
        w1.x * V[0] + w1.y * V[1] + w1.z * V[2],
        w1.x * V[1] + w1.y * V[3] + w1.z * V[4],
        w1.x * V[2] + w1.y * V[4] + w1.z * V[5],
      );
      let vxx = dot(a0, w0);
      let vxy = dot(a0, w1);
      let vyy = dot(a1, w1);

      let z = max(abs(depth), 1e-4);
      let jx = cu_u.focal.x / z;
      let jy = cu_u.focal.y / z;
      let reg = 0.3; // SF_EWA_DILATION
      let c00 = jx * jx * vxx + reg;
      let c01 = jx * jy * vxy;
      let c11 = jy * jy * vyy + reg;

      let half_trace = 0.5 * (c00 + c11);
      let det = max(c00 * c11 - c01 * c01, 0.0);
      let term = sqrt(max(half_trace * half_trace - det, 0.0));
      let lambda_max = max(half_trace + term, 0.0);
      let sigma = sqrt(lambda_max);

      // r_max - radius at which alpha * exp(-r^2 / 2 sigma^2) = tau.
      //   r_max^2 = 2 * sigma^2 * ln(alpha/tau).
      let ln_ratio = max(log(alpha / cu_u.tau), 0.0);
      let r_max = sigma * sqrt(2.0 * ln_ratio);

      // Sub-pixel cull.
      if (r_max >= 0.5) {
        alive = 1u;
      }
    }
  }

  cu_flag[i]   = alive;
  cu_prefix[i] = alive;
}

// =============================================================================
// cs_compact bindings:
//   0 (read)        : flag_buffer[]    (0/1 alive flag from cs_cull)
//   1 (read)        : prefix_buffer[]  (exclusive prefix sum, post-scan)
//   2 (read_write)  : compact_indices[]
//   3 (uniform)     : { splat_count, _pad, _pad, _pad }
// =============================================================================
struct CompactUniforms {
  splat_count: u32,
  _pad: vec3<u32>,
};
@group(0) @binding(0) var<storage, read>       co_flag    : array<u32>;
@group(0) @binding(1) var<storage, read>       co_prefix  : array<u32>;
@group(0) @binding(2) var<storage, read_write> co_compact : array<u32>;
@group(0) @binding(3) var<uniform>             co_u       : CompactUniforms;

@compute @workgroup_size(256)
fn cs_compact(@builtin(global_invocation_id) gid : vec3<u32>) {
  let i = gid.x;
  if (i >= co_u.splat_count) { return; }
  if (co_flag[i] == 1u) {
    co_compact[co_prefix[i]] = i;
  }
}

// =============================================================================
// cs_project_cmpct bindings (mirrors cs_project from decode.wgsl except for
// the compact_indices indirection at binding 5):
//   0 (read)        : splats[]
//   1 (read_write)  : inst[]
//   2 (read_write)  : keys[]
//   3 (read_write)  : values[]
//   4 (uniform)     : ProjectUniforms  (.splat_count = survivors)
//   5 (read)        : compact_indices[]
// Dispatch shape: ceil(survivors / 256).
// =============================================================================
struct ProjectUniforms {
  view: mat4x4<f32>,
  view_proj: mat4x4<f32>,
  viewport: vec2<f32>,
  focal:    vec2<f32>,
  splat_count: u32,
  _pad: u32,
  _pad2: vec2<u32>,
};
@group(0) @binding(0) var<storage, read>       pc_splats   : array<DecodedSplat>;
@group(0) @binding(1) var<storage, read_write> pc_inst     : array<Instance>;
@group(0) @binding(2) var<storage, read_write> pc_keys     : array<u32>;
@group(0) @binding(3) var<storage, read_write> pc_indices  : array<u32>;
@group(0) @binding(4) var<uniform>             pc_u        : ProjectUniforms;
@group(0) @binding(5) var<storage, read>       pc_compact  : array<u32>;

fn cov3d_pc(scale: vec3<f32>, q: vec4<f32>) -> array<f32, 6> {
  let n = max(length(q), 1e-8);
  let qn = q / n;
  let x = qn.x; let y = qn.y; let z = qn.z; let w = qn.w;
  let xx = x*x; let yy = y*y; let zz = z*z;
  let xy = x*y; let xz = x*z; let yz = y*z;
  let wx = w*x; let wy = w*y; let wz = w*z;
  let r00 = 1.0 - 2.0*(yy + zz);
  let r10 = 2.0*(xy + wz);
  let r20 = 2.0*(xz - wy);
  let r01 = 2.0*(xy - wz);
  let r11 = 1.0 - 2.0*(xx + zz);
  let r21 = 2.0*(yz + wx);
  let r02 = 2.0*(xz + wy);
  let r12 = 2.0*(yz - wx);
  let r22 = 1.0 - 2.0*(xx + yy);
  let sx = scale.x; let sy = scale.y; let sz = scale.z;
  let m00 = r00*sx; let m10 = r10*sx; let m20 = r20*sx;
  let m01 = r01*sy; let m11 = r11*sy; let m21 = r21*sy;
  let m02 = r02*sz; let m12 = r12*sz; let m22 = r22*sz;
  return array<f32, 6>(
    m00*m00 + m01*m01 + m02*m02,
    m00*m10 + m01*m11 + m02*m12,
    m00*m20 + m01*m21 + m02*m22,
    m10*m10 + m11*m11 + m12*m12,
    m10*m20 + m11*m21 + m12*m22,
    m20*m20 + m21*m21 + m22*m22,
  );
}

@compute @workgroup_size(256)
fn cs_project_cmpct(@builtin(global_invocation_id) gid : vec3<u32>) {
  let i = gid.x;
  if (i >= pc_u.splat_count) { return; }   // splat_count here = survivors

  let si = pc_compact[i];
  let s = pc_splats[si];
  let pos = s.pos.xyz;
  let opacity = s.pos.w;

  let clip = pc_u.view_proj * vec4<f32>(pos, 1.0);
  let invW = select(1.0, 1.0 / clip.w, abs(clip.w) > 1e-12);
  let ndc = vec3<f32>(clip.x * invW, clip.y * invW, clip.z * invW);

  let vz = pc_u.view[0][2] * pos.x + pc_u.view[1][2] * pos.y + pc_u.view[2][2] * pos.z + pc_u.view[3][2];
  let depth = -vz;
  let behind = depth <= 0.0;

  let V = cov3d_pc(s.scale.xyz, s.rot);
  let w0 = vec3<f32>(pc_u.view[0][0], pc_u.view[1][0], pc_u.view[2][0]);
  let w1 = vec3<f32>(pc_u.view[0][1], pc_u.view[1][1], pc_u.view[2][1]);
  let a0 = vec3<f32>(
    w0.x * V[0] + w0.y * V[1] + w0.z * V[2],
    w0.x * V[1] + w0.y * V[3] + w0.z * V[4],
    w0.x * V[2] + w0.y * V[4] + w0.z * V[5],
  );
  let a1 = vec3<f32>(
    w1.x * V[0] + w1.y * V[1] + w1.z * V[2],
    w1.x * V[1] + w1.y * V[3] + w1.z * V[4],
    w1.x * V[2] + w1.y * V[4] + w1.z * V[5],
  );
  let vxx = dot(a0, w0);
  let vxy = dot(a0, w1);
  let vyy = dot(a1, w1);

  let z = max(abs(depth), 1e-4);
  let jx = pc_u.focal.x / z;
  let jy = pc_u.focal.y / z;
  let reg = 0.3; // SF_EWA_DILATION
  let c00 = jx * jx * vxx + reg;
  let c01 = jx * jy * vxy;
  let c11 = jy * jy * vyy + reg;

  let half_trace = 0.5 * (c00 + c11);
  let det = max(c00 * c11 - c01 * c01, 0.0);
  let term = sqrt(max(half_trace * half_trace - det, 0.0));
  let lambda_max = half_trace + term;
  var radius = 3.0 * sqrt(max(lambda_max, 0.0));
  if (behind) { radius = 0.0; }

  var inst: Instance;
  let zc = clamp(ndc.z, 0.0, 1.0);
  if (behind) {
    inst.clip_pos = vec4<f32>(2.0, 2.0, 1.0, 1.0);
    inst.cov      = vec4<f32>(1.0, 0.0, 1.0, 0.0);
  } else {
    inst.clip_pos = vec4<f32>(ndc.xy, zc, clip.w);
    inst.cov      = vec4<f32>(c00, c01, c11, radius);
  }
  inst.color = vec4<f32>(s.color.rgb, opacity);
  pc_inst[i] = inst;

  let dpos = max(depth, 0.0);
  let kd = bitcast<u32>(dpos);
  pc_keys[i] = 0xffffffffu - kd;
  pc_indices[i] = i;
}
`;

export const WSR_CLEAR_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// WSR per-frame accumulator clear.
//
// Zeros the numerator (RGB + unused, packed as 4 × u32-bitcast-of-f32) and
// denominator (1 × u32-bitcast-of-f32) atomic accumulator buffers at the
// start of each frame. WebGPU 1.0 has no portable storage-buffer clear
// command for atomic-typed bindings, so we do it in a compute kernel.
//
// 16 × 16 workgroup; one invocation per pixel. Each invocation writes 5 u32s.
//
// Buffer layout (must match cs_wsr_accumulate.wgsl and cs_wsr_resolve.wgsl):
//   numerator[px*4 + 0] = bit-pattern of f32 Σ (α·w·c.r)
//   numerator[px*4 + 1] = bit-pattern of f32 Σ (α·w·c.g)
//   numerator[px*4 + 2] = bit-pattern of f32 Σ (α·w·c.b)
//   numerator[px*4 + 3] = 0 (unused; kept for 16-byte vec4 alignment)
//   denominator[px]     = bit-pattern of f32 Σ (α·w)
//
// Zero is the bit-pattern 0x00000000 for both signed-zero f32 and u32, so a
// plain \`atomicStore(..., 0u)\` is correct and sets the accumulator to +0.0.

struct ClearUniforms {
  viewport: vec2<u32>,
  _pad:     vec2<u32>,
};

@group(0) @binding(0) var<storage, read_write> numerator   : array<atomic<u32>>;
@group(0) @binding(1) var<storage, read_write> denominator : array<atomic<u32>>;
@group(0) @binding(2) var<uniform>             cu          : ClearUniforms;

@compute @workgroup_size(16, 16)
fn cs_wsr_clear(@builtin(global_invocation_id) gid : vec3<u32>) {
  let x = gid.x;
  let y = gid.y;
  if (x >= cu.viewport.x || y >= cu.viewport.y) { return; }
  let px = y * cu.viewport.x + x;
  atomicStore(&numerator[px * 4u + 0u], 0u);
  atomicStore(&numerator[px * 4u + 1u], 0u);
  atomicStore(&numerator[px * 4u + 2u], 0u);
  atomicStore(&numerator[px * 4u + 3u], 0u);
  atomicStore(&denominator[px], 0u);
}
`;

export const WSR_ACCUMULATE_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// WSR scatter accumulate (Hou et al. 2024, LC-WSR variant).
//
// One thread per splat. Each thread:
//   1. Reads \`splats[i]\` directly — no g_indices[] indirection, no sort.
//   2. Projects to NDC + 2D screen-space covariance using the same math as
//      cs_project / cs_project_gather (kept byte-identical so the projection
//      regression tests in __tests__/webgpu/fused_project_gather still
//      enforce parity if the legacy sorted-alpha path is ever re-enabled).
//   3. Computes the per-splat depth weight  w_i = max(0, 1 - d_i/σ - v_i).
//      PR1 ships with v_i = 0 globally (no per-splat-bias storage); the σ
//      uniform is set host-side from the scene bounding box (2 × mean depth).
//   4. Walks the [cx - r, cx + r] × [cy - r, cy + r] axis-aligned bounding
//      box around the projected splat center in screen-space pixels. For
//      each covered pixel, evaluates the 2D Gaussian:
//          power = -0.5 · (dx² · inv00 + 2 · dx · dy · inv01 + dy² · inv11)
//          α_eff = α_i · exp(power)              (clamped to [0, 0.999])
//      and scatter-adds:
//          numerator[px]   += α_eff · w_i · c_i   (vec3)
//          denominator[px] += α_eff · w_i         (scalar)
//      via a CAS-loop emulated atomic-add on u32-bitcasted f32 (storage-
//      buffer atomic-float is not in WebGPU 1.0; the CAS loop is the
//      portable shim documented in B7.1 EXECUTION-LOG.)
//
// Numerical notes:
//   - Both \`power > 0\` (outside ellipse) and \`α_eff < 1/255\` are early-exit
//     fragment-discard heuristics inherited from fs_main in renderer/webgpu.ts.
//     They preserve the visible-pixel set of the existing rasterizer so
//     downstream parity testing can compare PSNR fairly.
//   - The CAS loop is bounded by a hard iteration cap (256) to keep the
//     shader well-behaved under pathological contention. In practice the
//     B7.1 measurement on the laptop 4090 showed scatter is DRAM-bound, not
//     atomic-bound, so the loop terminates after 1-2 iterations on average
//     even at 10 M splats × 16 px² median footprint.
//   - Behind-camera and zero-radius splats are filtered identically to
//     cs_project_gather so the WSR path's culled set is a strict subset of
//     the rasterized set (no spurious accumulation behind the camera).

struct DecodedSplat {
  pos:   vec4<f32>,  // xyz = world position, w = opacity
  scale: vec4<f32>,  // xyz = scale, w = reserved
  rot:   vec4<f32>,  // quaternion (x,y,z,w)
  color: vec4<f32>,  // rgb = DC SH coefficient, a = reserved
};

struct WSRUniforms {
  view:        mat4x4<f32>,
  view_proj:   mat4x4<f32>,
  viewport:    vec2<f32>,
  focal:       vec2<f32>,
  splat_count: u32,
  _pad0:       u32,
  // Per-frame WSR parameters. PR1 uses a single scene-wide σ derived host-
  // side from \`2 × scene_mean_depth\`; PR3 replaces this with a learned σ
  // baked into the manifest. v_i is treated as 0 in PR1 (no per-splat
  // storage allocated).
  sigma:       f32,
  v_default:   f32,
  // Viewport size redundantly as u32 to avoid float-to-int conversions in
  // the inner pixel loop; matches the ClearUniforms layout.
  viewport_u:  vec2<u32>,
};

@group(0) @binding(0) var<storage, read>       splats      : array<DecodedSplat>;
@group(0) @binding(1) var<storage, read_write> numerator   : array<atomic<u32>>;
@group(0) @binding(2) var<storage, read_write> denominator : array<atomic<u32>>;
@group(0) @binding(3) var<uniform>             u           : WSRUniforms;

// Same upper-triangular 3D covariance as cov3d_fg in cs_project_gather.wgsl.
fn cov3d_w(scale: vec3<f32>, q: vec4<f32>) -> array<f32, 6> {
  let n = max(length(q), 1e-8);
  let qn = q / n;
  let x = qn.x; let y = qn.y; let z = qn.z; let w = qn.w;
  let xx = x*x; let yy = y*y; let zz = z*z;
  let xy = x*y; let xz = x*z; let yz = y*z;
  let wx = w*x; let wy = w*y; let wz = w*z;
  let r00 = 1.0 - 2.0*(yy + zz);
  let r10 = 2.0*(xy + wz);
  let r20 = 2.0*(xz - wy);
  let r01 = 2.0*(xy - wz);
  let r11 = 1.0 - 2.0*(xx + zz);
  let r21 = 2.0*(yz + wx);
  let r02 = 2.0*(xz + wy);
  let r12 = 2.0*(yz - wx);
  let r22 = 1.0 - 2.0*(xx + yy);
  let sx = scale.x; let sy = scale.y; let sz = scale.z;
  let m00 = r00*sx; let m10 = r10*sx; let m20 = r20*sx;
  let m01 = r01*sy; let m11 = r11*sy; let m21 = r21*sy;
  let m02 = r02*sz; let m12 = r12*sz; let m22 = r22*sz;
  return array<f32, 6>(
    m00*m00 + m01*m01 + m02*m02,
    m00*m10 + m01*m11 + m02*m12,
    m00*m20 + m01*m21 + m02*m22,
    m10*m10 + m11*m11 + m12*m12,
    m10*m20 + m11*m21 + m12*m22,
    m20*m20 + m21*m21 + m22*m22,
  );
}

// CAS-loop atomic float add. Returns nothing — best-effort with a hard cap
// to avoid livelock under pathological contention.
fn atomic_add_f32(slot: ptr<storage, atomic<u32>, read_write>, value: f32) {
  if (value == 0.0) { return; }
  var iter = 0u;
  loop {
    let current_u = atomicLoad(slot);
    let current_f = bitcast<f32>(current_u);
    let new_f = current_f + value;
    let new_u = bitcast<u32>(new_f);
    let res = atomicCompareExchangeWeak(slot, current_u, new_u);
    if (res.exchanged) { break; }
    iter = iter + 1u;
    if (iter >= 256u) { break; }
  }
}

@compute @workgroup_size(256)
fn cs_wsr_accumulate(@builtin(global_invocation_id) gid : vec3<u32>) {
  let i = gid.x;
  if (i >= u.splat_count) { return; }

  let s = splats[i];
  let pos = s.pos.xyz;
  let opacity = s.pos.w;

  // Clip-space + view-space depth. Same operation ordering as cs_project_gather.
  let clip = u.view_proj * vec4<f32>(pos, 1.0);
  let invW = select(1.0, 1.0 / clip.w, abs(clip.w) > 1e-12);
  let ndc = vec3<f32>(clip.x * invW, clip.y * invW, clip.z * invW);

  let vz = u.view[0][2] * pos.x + u.view[1][2] * pos.y + u.view[2][2] * pos.z + u.view[3][2];
  let depth = -vz;
  if (depth <= 0.0) { return; }

  // 2D screen-space covariance via the Jacobian of the perspective projection.
  let V = cov3d_w(s.scale.xyz, s.rot);
  let w0 = vec3<f32>(u.view[0][0], u.view[1][0], u.view[2][0]);
  let w1 = vec3<f32>(u.view[0][1], u.view[1][1], u.view[2][1]);
  let a0 = vec3<f32>(
    w0.x * V[0] + w0.y * V[1] + w0.z * V[2],
    w0.x * V[1] + w0.y * V[3] + w0.z * V[4],
    w0.x * V[2] + w0.y * V[4] + w0.z * V[5],
  );
  let a1 = vec3<f32>(
    w1.x * V[0] + w1.y * V[1] + w1.z * V[2],
    w1.x * V[1] + w1.y * V[3] + w1.z * V[4],
    w1.x * V[2] + w1.y * V[4] + w1.z * V[5],
  );
  let vxx = dot(a0, w0);
  let vxy = dot(a0, w1);
  let vyy = dot(a1, w1);

  let z = max(abs(depth), 1e-4);
  let jx = u.focal.x / z;
  let jy = u.focal.y / z;
  let reg = 0.3;
  let c00 = jx * jx * vxx + reg;
  let c01 = jx * jy * vxy;
  let c11 = jy * jy * vyy + reg;

  // 3σ pixel radius from the larger eigenvalue.
  let half_trace = 0.5 * (c00 + c11);
  let det = max(c00 * c11 - c01 * c01, 1e-6);
  let term = sqrt(max(half_trace * half_trace - det, 0.0));
  let lambda_max = half_trace + term;
  let radius = 3.0 * sqrt(max(lambda_max, 0.0));
  if (radius < 0.5) { return; }

  // Inverse covariance for Gaussian evaluation.
  let inv00 =  c11 / det;
  let inv01 = -c01 / det;
  let inv11 =  c00 / det;

  // LC-WSR depth weight. σ = 2 × mean_scene_depth in PR1 (no fine-tuning).
  let sigma = max(u.sigma, 1e-6);
  let v_i   = u.v_default;
  let w_d = max(0.0, 1.0 - depth / sigma - v_i);
  if (w_d <= 0.0) { return; }

  // Screen-space center in pixels (NDC y is flipped to match the renderer).
  let cx = (ndc.x * 0.5 + 0.5) * u.viewport.x;
  let cy = (1.0 - (ndc.y * 0.5 + 0.5)) * u.viewport.y;

  let r_pad = ceil(radius);
  let xmin = max(0,            i32(floor(cx - r_pad)));
  let ymin = max(0,            i32(floor(cy - r_pad)));
  let xmax = min(i32(u.viewport_u.x) - 1, i32(ceil(cx + r_pad)));
  let ymax = min(i32(u.viewport_u.y) - 1, i32(ceil(cy + r_pad)));
  if (xmin > xmax || ymin > ymax) { return; }

  let color = vec3<f32>(s.color.r, s.color.g, s.color.b);
  let alpha_base = clamp(opacity, 0.0, 1.0);

  // Cap the per-thread pixel walk to a generous upper bound. At the PR1
  // capacity (1.16M-3.62M real splats, sub-pixel median footprint) this is
  // effectively no-op; the cap exists so a single pathological splat at very
  // close range cannot stall the entire workgroup.
  let bbox_area = (xmax - xmin + 1) * (ymax - ymin + 1);
  if (bbox_area > 4096) { return; }

  for (var py = ymin; py <= ymax; py = py + 1) {
    for (var px = xmin; px <= xmax; px = px + 1) {
      let dx = f32(px) + 0.5 - cx;
      let dy = f32(py) + 0.5 - cy;
      let power = -0.5 * (dx * dx * inv00 + 2.0 * dx * dy * inv01 + dy * dy * inv11);
      if (power > 0.0) { continue; }
      let g = exp(power);
      let alpha = clamp(alpha_base * g, 0.0, 0.999);
      if (alpha < 1.0 / 255.0) { continue; }

      let aw = alpha * w_d;
      let pidx = u32(py) * u.viewport_u.x + u32(px);
      atomic_add_f32(&numerator[pidx * 4u + 0u], aw * color.r);
      atomic_add_f32(&numerator[pidx * 4u + 1u], aw * color.g);
      atomic_add_f32(&numerator[pidx * 4u + 2u], aw * color.b);
      atomic_add_f32(&denominator[pidx],         aw);
    }
  }
}
`;

export const WSR_RESOLVE_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// WSR resolve pass.
//
// Reads the per-pixel accumulator buffers (numerator RGB sum, denominator
// scalar sum) and computes the final RGB:
//
//     C_px = (w_B · c_B + N_px) / (w_B + D_px)
//
// with constants \`w_B = 1e-4\` and \`c_B = (0, 0, 0)\` (black background — PR1
// scope; scene-aware background is a PR5 follow-up). The 1e-4 floor on the
// denominator prevents division by zero where no splat covered the pixel.
//
// Writes the final RGBA (alpha = 1) to the output storage texture. The
// caller decides whether to present that texture to the canvas directly
// (renderer integration) or to read it back for offline comparison (the
// \`wsr.test.ts\` unit test path).
//
// Buffer layout (matches cs_wsr_clear.wgsl and cs_wsr_accumulate.wgsl):
//   numerator[px*4 + 0..2] = bit-pattern of f32 channel sums
//   numerator[px*4 + 3]    = 0 (unused, kept for vec4 alignment)
//   denominator[px]        = bit-pattern of f32 scalar sum

struct ResolveUniforms {
  viewport: vec2<u32>,
  _pad:     vec2<u32>,
  bg_color: vec4<f32>,  // (R, G, B, w_B). Default (0, 0, 0, 1e-4).
};

@group(0) @binding(0) var<storage, read>       numerator   : array<u32>;
@group(0) @binding(1) var<storage, read>       denominator : array<u32>;
@group(0) @binding(2) var<storage, read_write> output_rgba : array<u32>;
@group(0) @binding(3) var<uniform>             u           : ResolveUniforms;

// Pack a vec4<f32> RGBA in [0,1] into a single u32 with R in the low byte.
// Matches the canonical \`rgba8unorm\` byte order so the buffer can be used as
// a \`COPY_SRC\` for \`copyBufferToTexture(rgba8unorm, ...)\` downstream.
fn pack_rgba8(c: vec4<f32>) -> u32 {
  let v = clamp(c, vec4<f32>(0.0), vec4<f32>(1.0)) * 255.0 + vec4<f32>(0.5);
  let r = u32(v.x);
  let g = u32(v.y);
  let b = u32(v.z);
  let a = u32(v.w);
  return r | (g << 8u) | (b << 16u) | (a << 24u);
}

@compute @workgroup_size(16, 16)
fn cs_wsr_resolve(@builtin(global_invocation_id) gid : vec3<u32>) {
  let x = gid.x;
  let y = gid.y;
  if (x >= u.viewport.x || y >= u.viewport.y) { return; }
  let px = y * u.viewport.x + x;

  let n_r = bitcast<f32>(numerator[px * 4u + 0u]);
  let n_g = bitcast<f32>(numerator[px * 4u + 1u]);
  let n_b = bitcast<f32>(numerator[px * 4u + 2u]);
  let d   = bitcast<f32>(denominator[px]);

  let w_b   = u.bg_color.a;
  let c_b   = u.bg_color.rgb;
  let denom = w_b + d;
  let c     = (w_b * c_b + vec3<f32>(n_r, n_g, n_b)) / denom;

  output_rgba[px] = pack_rgba8(vec4<f32>(c.r, c.g, c.b, 1.0));
}
`;

export const LOD_SELECT_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// LODGE Phase A.3 — per-chunk LOD selection compute pass.
//
// One thread per chunk (workgroup 64). Reads the chunk's centroid + radius
// + per-level depth-threshold table, then writes a per-chunk activation
// record:
//
//   - \`level\`   : chosen LOD level for this chunk (0 = finest)
//   - \`active\`  : 1 = chunk is in the union of "near" + "far" slots this
//                 frame, 0 = drop. The runtime allocates \`active=1\` chunks
//                 to either the near slot or the far slot per LODGE eq. 4.
//   - \`slot\`    : 0 = near (camera-side), 1 = far (transition partner).
//                 Used by cs_lod_blend to read the correct centroid pair
//                 when computing the boundary-blend t-ramp.
//   - \`t_blend\` : LODGE eq. 4 boundary-blend parameter, normalized to
//                 [0, 1]. The runtime applies this as \`alpha' = alpha *
//                 t_blend\` for the symmetric-difference splats inside
//                 cs_lod_blend. Splats in the union intersection get
//                 \`t_blend = 1\` (fully opaque).
//
// The kernel is the GPU-side embodiment of LODGE eq. 2 (per-band active
// set) + eq. 4 (boundary-blend ramp). The CPU-side selector in
// \`lodge/manifest.ts::selectLodLevel\` is a coarser one-level-per-frame
// fallback that we keep for browsers without compute-shader access.
//
// Determinism: pure functions of (camera, chunk centroids, depth
// thresholds, per-level radius). No atomics, no inter-thread comms.
// Two runs with the same uniforms produce bit-identical outputs.
//
// Bind group:
//   0 (read)    : chunks[]              — ChunkDesc per chunk (all levels
//                                          flattened; level/index encoded in
//                                          the record).
//   1 (read)    : levels[]              — per-level uniform record
//                                          (depth_threshold, level index).
//                                          MAX_LOD_LEVELS = 8 slots; unused
//                                          entries carry depth_threshold =
//                                          +inf so the level is never
//                                          chosen.
//   2 (read_write) : chunk_activation[] — per-chunk output record.
//   3 (uniform) : LodSelectUniforms.

struct ChunkDesc {
  centroid: vec4<f32>,   // .xyz = centroid, .w = radius
  // The "owning" level for this chunk record. Phase A.3 emits one
  // ChunkDesc per (level, chunk_index); the kernel picks the level whose
  // depth-threshold band contains the camera distance.
  level: u32,
  chunk_index: u32,
  splat_count: u32,
  _pad: u32,
};

struct LevelDesc {
  depth_threshold: f32,  // LODGE eq. 2 band edge for this level
  level: u32,            // == array index, but stored for safety
  _pad0: u32,
  _pad1: u32,
};

struct ChunkActivation {
  level: u32,            // chosen level (0 if !active)
  active: u32,           // 1 = include this chunk this frame
  slot: u32,             // 0 = near, 1 = far
  t_blend: f32,          // LODGE eq. 4 ramp in [0, 1]
};

struct LodSelectUniforms {
  camera_pos:        vec4<f32>,   // .xyz = world-space camera position
  scene_center:      vec4<f32>,   // .xyz = scene-bbox centroid (anchor for
                                  //         level pick)
  // Per-level depth thresholds (LODGE eq. 2). We mirror the per-level
  // record in \`LevelDesc\` here for cache locality — one uniform read per
  // thread instead of an indirect into the level buffer.
  // depth_threshold[i] = nominal band edge for level i. depth_threshold[0]
  // is always 0. Unused slots are set to +inf.
  depth_thresholds:  vec4<f32>,   // levels 0..3
  depth_thresholds2: vec4<f32>,   // levels 4..7
  // Packed (chunk_count, num_levels, pad, pad) — explicit vec4-of-u32 to
  // keep WGSL alignment in lock-step with the JS-side byte encoder.
  // Without this packing, WGSL would silently pad after \`num_levels\` to
  // re-align \`near_centroid: vec4<f32>\`, and the JS encoder would have
  // to mirror that pad — easy to get wrong.
  counts:            vec4<u32>,
  // Near-chunk centroid for the boundary blend (LODGE eq. 4). The runtime
  // picks the camera-closest chunk on the CPU side and writes its centroid
  // here so the GPU has the m_o anchor for the ramp.
  near_centroid:     vec4<f32>,   // .xyz = m_o (closer-chunk centroid)
  far_centroid:      vec4<f32>,   // .xyz = m_f (transition partner)
  // (ss_size_threshold, focal_y, _pad, _pad) — same packing rationale as
  // \`counts\` above. Treat as a vec4<f32> so the WGSL struct is exactly 8
  // vec4 = 128 bytes total, identical to the JS encoder layout.
  ss_focal:          vec4<f32>,
};

@group(0) @binding(0) var<storage, read>       ls_chunks      : array<ChunkDesc>;
@group(0) @binding(1) var<storage, read>       ls_levels      : array<LevelDesc>;
@group(0) @binding(2) var<storage, read_write> ls_activation  : array<ChunkActivation>;
@group(0) @binding(3) var<uniform>             ls_u           : LodSelectUniforms;

/// Read level i's depth threshold from the packed vec4 uniforms.
fn depth_threshold_at(i: u32) -> f32 {
  switch (i) {
    case 0u: { return ls_u.depth_thresholds.x; }
    case 1u: { return ls_u.depth_thresholds.y; }
    case 2u: { return ls_u.depth_thresholds.z; }
    case 3u: { return ls_u.depth_thresholds.w; }
    case 4u: { return ls_u.depth_thresholds2.x; }
    case 5u: { return ls_u.depth_thresholds2.y; }
    case 6u: { return ls_u.depth_thresholds2.z; }
    default: { return ls_u.depth_thresholds2.w; }
  }
}

/// LODGE eq. 4 boundary-blend ramp. Computes the projection of
/// \`(c - m_o)\` onto \`(m_f - m_o)\`, normalized by \`||m_o - m_f||²\`, clamped
/// to [0, 1]. The result is 0 when the camera is at m_o, 1 when at m_f.
/// For symmetric-difference splats: opacity multiplier is t for splats
/// owned by m_f, (1 - t) for splats owned by m_o. Intersection splats keep
/// t = 1.
fn boundary_blend_t(camera: vec3<f32>, m_o: vec3<f32>, m_f: vec3<f32>) -> f32 {
  let v = m_f - m_o;
  let denom = max(dot(v, v), 1e-8);
  let raw = dot(camera - m_o, v) / denom;
  return clamp(raw, 0.0, 1.0);
}

@compute @workgroup_size(64)
fn cs_lod_select(@builtin(global_invocation_id) gid: vec3<u32>) {
  let i = gid.x;
  if (i >= ls_u.counts.x) { return; }

  let chunk = ls_chunks[i];
  let centroid = chunk.centroid.xyz;
  let radius = chunk.centroid.w;
  let camera = ls_u.camera_pos.xyz;

  // Distance from camera to chunk centroid (eq. 2 anchor).
  let dvec = camera - centroid;
  let dist = sqrt(dot(dvec, dvec));
  // LODGE allows a "near" slack of \`radius\` so chunks at the camera edge
  // don't pop. Subtract the chunk radius from the band-edge comparison.
  let dist_eff = max(dist - radius, 0.0);

  // ----- Camera-distance band: pick the coarsest level whose
  //       depth_threshold ≤ dist_eff. -----
  var chosen_level: u32 = 0u;
  for (var l: u32 = 0u; l < ls_u.counts.y; l = l + 1u) {
    let t = depth_threshold_at(l);
    if (dist_eff >= t) {
      chosen_level = l;
    }
  }

  // ----- Screen-space size heuristic: if the chunk's projected screen
  //       radius (focal * radius / dist) drops below the SS threshold,
  //       bump to the next coarser level. -----
  let safe_dist = max(dist, 1e-3);
  let ss_radius = ls_u.ss_focal.y * radius / safe_dist;
  if (ss_radius < ls_u.ss_focal.x && chosen_level + 1u < ls_u.counts.y) {
    chosen_level = chosen_level + 1u;
  }

  // ----- Activation: a chunk is active iff its own record's level matches
  //       the chosen level. The runtime emits one ChunkDesc per
  //       (level, chunk_index); only the records on the chosen level get
  //       \`active = 1\`. This is the GPU-side embodiment of "select the
  //       right LOD level for this spatial region".
  var act: ChunkActivation;
  act.level = chosen_level;
  act.active = 0u;
  act.slot = 0u;
  act.t_blend = 1.0;

  if (chunk.level == chosen_level) {
    act.active = 1u;

    // ----- Slot + boundary blend. Compute distance from this chunk's
    //       centroid to the near and far centroids; this chunk lives in
    //       the slot whose centroid is closer.
    let d_near = length(centroid - ls_u.near_centroid.xyz);
    let d_far  = length(centroid - ls_u.far_centroid.xyz);
    let is_far = d_far < d_near;
    act.slot = select(0u, 1u, is_far);

    // ----- LODGE eq. 4 t-ramp. The blend parameter is shared by every
    //       chunk in the active union; we evaluate it once per chunk so
    //       the downstream blend kernel can apply it as a per-splat
    //       opacity multiplier without re-fetching the uniforms. -----
    let t = boundary_blend_t(camera, ls_u.near_centroid.xyz, ls_u.far_centroid.xyz);
    // Near chunk: opacity *= (1 - t). Far chunk: opacity *= t. We store
    // the per-chunk multiplier directly so the blend kernel doesn't have
    // to branch on slot.
    act.t_blend = select(1.0 - t, t, is_far);

    // For chunks in BOTH near and far set ranges (i.e. intersection),
    // the runtime collapses the duplicate by setting t_blend = 1 on the
    // canonical entry. Detection: if near == far centroids, this is a
    // single-chunk pinch; force t = 1.
    let near_eq_far = distance(ls_u.near_centroid.xyz, ls_u.far_centroid.xyz) < 1e-4;
    if (near_eq_far) {
      act.t_blend = 1.0;
    }
  }

  ls_activation[i] = act;
}
`;

export const LOD_BLEND_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// LODGE Phase A.3 — per-splat boundary-blend opacity modulation
// (LODGE eq. 4).
//
// Input  : decoded splats[] (the canonical 64-byte DecodedSplat layout)
//          + per-splat \`chunk_id\` side buffer
//          + per-chunk activation records (output of cs_lod_select)
// Output : modulated splats[] (opacity field rewritten with t_blend)
//
// Pipeline:
//
//   1. cs_lod_select decided per-chunk \`active\` + per-chunk \`t_blend\`.
//   2. This kernel touches every decoded splat, looks up its chunk's
//      activation record, and writes:
//        - If \`active == 0\`: opacity := 0 (the splat is dropped by the
//          downstream cull predicate which gates on opacity ≥ tau).
//        - If \`active == 1\`: opacity := opacity * t_blend.
//      In both cases the splat record stays in the buffer; the cull /
//      sort / project flow handles the rest. We never delete splats —
//      just zero their alpha so the existing fast-path predicate prunes
//      them with no extra plumbing.
//
// Determinism: 1 thread per splat, pure functional update to splat.pos.w
// (which is where the canonical decoded splat stores opacity — see
// DecodedSplat struct in decode.wgsl).
//
// Math: LODGE paper eq. 4. The per-chunk multiplier is pre-computed in
// cs_lod_select (boundary_blend_t + slot resolution) so this kernel is
// branch-free per splat. The "near" chunk gets \`t_blend = 1 - t\` and the
// "far" chunk gets \`t_blend = t\`; intersection / single-chunk pinch gets
// \`t_blend = 1\`.

struct DecodedSplat {
  pos:   vec4<f32>,   // .xyz position, .w opacity
  scale: vec4<f32>,
  rot:   vec4<f32>,
  color: vec4<f32>,
};

struct ChunkActivation {
  level:   u32,
  active:  u32,
  slot:    u32,
  t_blend: f32,
};

struct LodBlendUniforms {
  splat_count: u32,
  // We can't reach the activation buffer via an SoA chunk_id directly
  // (chunk_ids are stored alongside splats but indexed per-splat). The
  // host packs the active set as a flattened per-splat u32 — the
  // \`chunk_id\` side buffer — so the GPU just does a single indirect
  // lookup. The activation buffer is indexed by chunk_id.
  chunk_count: u32,
  // When \`force_passthrough == 1\`, this kernel becomes a no-op (used by
  // the test harness to bypass the blend without re-creating buffers).
  force_passthrough: u32,
  _pad: u32,
};

@group(0) @binding(0) var<storage, read_write> lb_splats     : array<DecodedSplat>;
@group(0) @binding(1) var<storage, read>       lb_chunk_id   : array<u32>;
@group(0) @binding(2) var<storage, read>       lb_activation : array<ChunkActivation>;
@group(0) @binding(3) var<uniform>             lb_u          : LodBlendUniforms;

@compute @workgroup_size(256)
fn cs_lod_blend(@builtin(global_invocation_id) gid: vec3<u32>) {
  let i = gid.x;
  if (i >= lb_u.splat_count) { return; }
  if (lb_u.force_passthrough == 1u) { return; }

  let cid = lb_chunk_id[i];
  // Bounds-check: out-of-range chunk_id implies a streaming bug; drop
  // the splat by zeroing its opacity instead of letting the OOB read
  // poison the activation.
  if (cid >= lb_u.chunk_count) {
    lb_splats[i].pos.w = 0.0;
    return;
  }

  let act = lb_activation[cid];

  // Active chunks: modulate opacity by the LODGE eq. 4 ramp.
  // Inactive chunks (wrong level for this camera, OR culled by the
  // CPU-side budgetier): zero the alpha so the cull/project pipeline
  // skips them.
  var alpha = lb_splats[i].pos.w;
  if (act.active == 0u) {
    alpha = 0.0;
  } else {
    alpha = alpha * act.t_blend;
  }
  lb_splats[i].pos.w = alpha;
}

// =============================================================================
// cs_lod_blend_reset — restore splat opacities from a backup buffer.
//
// The blend kernel mutates \`splats[].pos.w\` in place. To support the
// "blend → project → restore → re-blend next frame" cycle without
// re-decoding the chunks, we keep a side \`original_alpha[]\` buffer
// populated at chunk-upload time, and this kernel writes it back into
// the splat records before each new blend. This is cheaper than
// re-decoding (which would re-run cs_decode over the same SoA bytes).
//
// Bind group:
//   0 (read_write) : splats[]
//   1 (read)       : original_alpha[]   (f32, 1 per splat)
//   2 (uniform)    : { splat_count, _pad×3 }
// =============================================================================
struct ResetUniforms {
  splat_count: u32,
  _pad: vec3<u32>,
};

@group(0) @binding(0) var<storage, read_write> lr_splats : array<DecodedSplat>;
@group(0) @binding(1) var<storage, read>       lr_alpha  : array<f32>;
@group(0) @binding(2) var<uniform>             lr_u      : ResetUniforms;

@compute @workgroup_size(256)
fn cs_lod_alpha_reset(@builtin(global_invocation_id) gid: vec3<u32>) {
  let i = gid.x;
  if (i >= lr_u.splat_count) { return; }
  lr_splats[i].pos.w = lr_alpha[i];
}
`;
