// SPDX-License-Identifier: Apache-2.0
// AUTO-GENERATED by scripts/embed-wgsl.mjs — DO NOT EDIT.
// Source files: src/webgpu/decode.wgsl, src/webgpu/radix_sort.wgsl,
//               src/webgpu/scan_multiblock.wgsl.

export const DECODE_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// WebGPU compute decode shader for SplatForge SoA splat chunks.
//
// Input  (storage, read):  packed bytes of a single chunk laid out as
//                          POSITION u16x3 normalized  | min, max from uniform
//                          ROTATION f32x4
//                          SCALE    u8x3  normalized  | min, max from uniform
//                          OPACITY  u8    normalized  | min=0, max=1
//                          COLOR_DC u8x3  normalized  | min=0, max=1
//
// Output (storage, write): array<DecodedSplat> — one record per splat in the
//                          canonical decoded form fed to the project pass.
//
// One workgroup-thread = one splat. Workgroup size 256 chosen to comfortably
// fit on every WebGPU implementation (Apple Silicon, Adreno, Mali) without
// hitting the 16384-byte workgroup shared-memory cap; we don't use shared
// memory in this pass.
//
// The math mirrors \`decodeAttribute\` in renderer/base.ts so the GPU and CPU
// paths produce bit-identical results modulo float-precision noise.

struct DecodedSplat {
  // vec4 packing keeps storage-buffer alignment at 16B. The shader emits
  //   pos.xyz   = world position
  //   pos.w     = opacity (so we save 12 bytes vs a separate vec4).
  //   scale.xyz = anisotropic scale
  //   scale.w   = reserved (0)
  //   rot.xyzw  = quaternion (x,y,z,w)
  //   color.rgb = DC SH coefficient as linear RGB
  //   color.a   = reserved (1)
  pos:   vec4<f32>,
  scale: vec4<f32>,
  rot:   vec4<f32>,
  color: vec4<f32>,
};

struct AttributeSlice {
  byte_offset: u32,
  // Each element is f32 even for ints — we burn 16B per slice but get
  // straight-line WGSL with no scalar-load conversions.
  comp_type:   u32, // 5121 u8, 5123 u16, 5126 f32
  normalized:  u32, // 0/1
  _pad:        u32,
  // Per-component dequant bounds. comp 0..3.
  vmin: vec4<f32>,
  vmax: vec4<f32>,
};

struct DecodeUniforms {
  splat_count: u32,
  _pad0: u32,
  _pad1: u32,
  _pad2: u32,
  positions: AttributeSlice,
  rotations: AttributeSlice,
  scales:    AttributeSlice,
  opacities: AttributeSlice,
  color_dc:  AttributeSlice,
};

@group(0) @binding(0) var<storage, read>       src_bytes : array<u32>;
@group(0) @binding(1) var<storage, read_write> dst_splats : array<DecodedSplat>;
@group(0) @binding(2) var<uniform>             u : DecodeUniforms;

// Load an unsigned byte from a u32 storage buffer at absolute byte offset \`b\`.
fn load_u8(b: u32) -> u32 {
  let word = src_bytes[b >> 2u];
  let sh   = (b & 3u) * 8u;
  return (word >> sh) & 0xffu;
}

// Load an unsigned 16-bit little-endian short.
fn load_u16(b: u32) -> u32 {
  // Two byte fetches always work, including across u32 boundaries. The two
  // are folded by the driver when aligned.
  let lo = load_u8(b);
  let hi = load_u8(b + 1u);
  return lo | (hi << 8u);
}

// Load a little-endian f32 by reading 4 contiguous bytes. WebGPU storage
// buffers are byte-addressable but not byte-typed; we reassemble.
fn load_f32(b: u32) -> f32 {
  let b0 = load_u8(b);
  let b1 = load_u8(b + 1u);
  let b2 = load_u8(b + 2u);
  let b3 = load_u8(b + 3u);
  return bitcast<f32>(b0 | (b1 << 8u) | (b2 << 16u) | (b3 << 24u));
}

// Decode one scalar attribute component at byte offset \`b\` according to
// the slice's comp_type / normalized / min / max.
fn decode_component(slice: AttributeSlice, b: u32, k: u32) -> f32 {
  if (slice.comp_type == 5126u) {
    return load_f32(b);
  }
  if (slice.comp_type == 5123u) {
    let raw = f32(load_u16(b));
    if (slice.normalized == 1u) {
      let lo = slice.vmin[k];
      let hi = slice.vmax[k];
      return lo + (raw / 65535.0) * (hi - lo);
    }
    return raw;
  }
  // default: 5121 u8
  let raw = f32(load_u8(b));
  if (slice.normalized == 1u) {
    let lo = slice.vmin[k];
    let hi = slice.vmax[k];
    return lo + (raw / 255.0) * (hi - lo);
  }
  return raw;
}

fn comp_stride(slice: AttributeSlice) -> u32 {
  if (slice.comp_type == 5126u) { return 4u; }
  if (slice.comp_type == 5123u) { return 2u; }
  return 1u;
}

@compute @workgroup_size(256)
fn cs_decode(@builtin(global_invocation_id) gid : vec3<u32>) {
  let i = gid.x;
  if (i >= u.splat_count) { return; }

  // POSITION (vec3)
  let p_stride = comp_stride(u.positions);
  let p_base = u.positions.byte_offset + i * 3u * p_stride;
  let px = decode_component(u.positions, p_base + 0u * p_stride, 0u);
  let py = decode_component(u.positions, p_base + 1u * p_stride, 1u);
  let pz = decode_component(u.positions, p_base + 2u * p_stride, 2u);

  // ROTATION (vec4) — always f32 on the wire today.
  let r_stride = comp_stride(u.rotations);
  let r_base = u.rotations.byte_offset + i * 4u * r_stride;
  let rx = decode_component(u.rotations, r_base + 0u * r_stride, 0u);
  let ry = decode_component(u.rotations, r_base + 1u * r_stride, 1u);
  let rz = decode_component(u.rotations, r_base + 2u * r_stride, 2u);
  let rw = decode_component(u.rotations, r_base + 3u * r_stride, 3u);

  // SCALE (vec3)
  let s_stride = comp_stride(u.scales);
  let s_base = u.scales.byte_offset + i * 3u * s_stride;
  let sx = decode_component(u.scales, s_base + 0u * s_stride, 0u);
  let sy = decode_component(u.scales, s_base + 1u * s_stride, 1u);
  let sz = decode_component(u.scales, s_base + 2u * s_stride, 2u);

  // OPACITY (scalar)
  let o_stride = comp_stride(u.opacities);
  let opacity = decode_component(u.opacities, u.opacities.byte_offset + i * o_stride, 0u);

  // COLOR_DC (vec3)
  let c_stride = comp_stride(u.color_dc);
  let c_base = u.color_dc.byte_offset + i * 3u * c_stride;
  let cr = decode_component(u.color_dc, c_base + 0u * c_stride, 0u);
  let cg = decode_component(u.color_dc, c_base + 1u * c_stride, 1u);
  let cb = decode_component(u.color_dc, c_base + 2u * c_stride, 2u);

  var out: DecodedSplat;
  out.pos   = vec4<f32>(px, py, pz, opacity);
  out.scale = vec4<f32>(sx, sy, sz, 0.0);
  out.rot   = vec4<f32>(rx, ry, rz, rw);
  out.color = vec4<f32>(cr, cg, cb, 1.0);
  dst_splats[i] = out;
}

// ---------------------------------------------------------------------------
// Project pass: canonical splats + camera → per-instance render attributes
// (clipPos, 2D covariance, premultiplied color) + sortable depth keys.
// ---------------------------------------------------------------------------

struct ProjectUniforms {
  view: mat4x4<f32>,
  view_proj: mat4x4<f32>,
  viewport: vec2<f32>,
  focal:    vec2<f32>,
  splat_count: u32,
  _pad: u32,
  _pad2: vec2<u32>,
};

// Per-instance vertex-buffer record (must match FLOATS_PER_INSTANCE=12).
struct Instance {
  clip_pos: vec4<f32>,
  cov:      vec4<f32>,
  color:    vec4<f32>,
};

@group(0) @binding(0) var<storage, read>       p_splats   : array<DecodedSplat>;
@group(0) @binding(1) var<storage, read_write> p_inst     : array<Instance>;
@group(0) @binding(2) var<storage, read_write> p_keys     : array<u32>;
@group(0) @binding(3) var<storage, read_write> p_indices  : array<u32>;
@group(0) @binding(4) var<uniform>             pu : ProjectUniforms;

// Build the upper-triangular 3D covariance Σ = R · diag(s²) · Rᵀ.
// Returns the six unique entries as (σxx, σxy, σxz, σyy, σyz, σzz).
fn cov3d(scale: vec3<f32>, q: vec4<f32>) -> array<f32, 6> {
  // Normalize the quaternion defensively (mirrors quatToMat3).
  let n = max(length(q), 1e-8);
  let qn = q / n;
  let x = qn.x; let y = qn.y; let z = qn.z; let w = qn.w;
  let xx = x*x; let yy = y*y; let zz = z*z;
  let xy = x*y; let xz = x*z; let yz = y*z;
  let wx = w*x; let wy = w*y; let wz = w*z;
  // Column-major rotation matrix.
  let r00 = 1.0 - 2.0*(yy + zz);
  let r10 = 2.0*(xy + wz);
  let r20 = 2.0*(xz - wy);
  let r01 = 2.0*(xy - wz);
  let r11 = 1.0 - 2.0*(xx + zz);
  let r21 = 2.0*(yz + wx);
  let r02 = 2.0*(xz + wy);
  let r12 = 2.0*(yz - wx);
  let r22 = 1.0 - 2.0*(xx + yy);
  let sx = scale.x; let sy = scale.y; let sz = scale.z;
  let m00 = r00*sx; let m10 = r10*sx; let m20 = r20*sx;
  let m01 = r01*sy; let m11 = r11*sy; let m21 = r21*sy;
  let m02 = r02*sz; let m12 = r12*sz; let m22 = r22*sz;
  return array<f32, 6>(
    m00*m00 + m01*m01 + m02*m02,
    m00*m10 + m01*m11 + m02*m12,
    m00*m20 + m01*m21 + m02*m22,
    m10*m10 + m11*m11 + m12*m12,
    m10*m20 + m11*m21 + m12*m22,
    m20*m20 + m21*m21 + m22*m22,
  );
}

@compute @workgroup_size(256)
fn cs_project(@builtin(global_invocation_id) gid : vec3<u32>) {
  let i = gid.x;
  if (i >= pu.splat_count) { return; }

  let s = p_splats[i];
  let pos = s.pos.xyz;
  let opacity = s.pos.w;

  // Clip-space.
  let clip = pu.view_proj * vec4<f32>(pos, 1.0);
  let invW = select(1.0, 1.0 / clip.w, abs(clip.w) > 1e-12);
  let ndc = vec3<f32>(clip.x * invW, clip.y * invW, clip.z * invW);

  // View-space depth: column-major mat4x4 indexed as m[col][row]; row 2 of the
  // view matrix dotted with (pos, 1) is \`-z\` of the view-space point.
  let vz = pu.view[0][2] * pos.x + pu.view[1][2] * pos.y + pu.view[2][2] * pos.z + pu.view[3][2];
  let depth = -vz;
  let behind = depth <= 0.0;

  // Reconstruct 3D covariance, project into 2D screen covariance.
  let V = cov3d(s.scale.xyz, s.rot);
  // Symmetric Σ entries:
  //   V[0]=σxx, V[1]=σxy, V[2]=σxz, V[3]=σyy, V[4]=σyz, V[5]=σzz.
  // World→view rotation rows.
  let w0 = vec3<f32>(pu.view[0][0], pu.view[1][0], pu.view[2][0]);
  let w1 = vec3<f32>(pu.view[0][1], pu.view[1][1], pu.view[2][1]);
  let a0 = vec3<f32>(
    w0.x * V[0] + w0.y * V[1] + w0.z * V[2],
    w0.x * V[1] + w0.y * V[3] + w0.z * V[4],
    w0.x * V[2] + w0.y * V[4] + w0.z * V[5],
  );
  let a1 = vec3<f32>(
    w1.x * V[0] + w1.y * V[1] + w1.z * V[2],
    w1.x * V[1] + w1.y * V[3] + w1.z * V[4],
    w1.x * V[2] + w1.y * V[4] + w1.z * V[5],
  );
  let vxx = dot(a0, w0);
  let vxy = dot(a0, w1);
  let vyy = dot(a1, w1);

  let z = max(abs(depth), 1e-4);
  let jx = pu.focal.x / z;
  let jy = pu.focal.y / z;
  let reg = 0.3;
  let c00 = jx * jx * vxx + reg;
  let c01 = jx * jy * vxy;
  let c11 = jy * jy * vyy + reg;

  // 3σ radius (px) from largest eigenvalue of the 2x2.
  let half_trace = 0.5 * (c00 + c11);
  let det = max(c00 * c11 - c01 * c01, 0.0);
  let term = sqrt(max(half_trace * half_trace - det, 0.0));
  let lambda_max = half_trace + term;
  var radius = 3.0 * sqrt(max(lambda_max, 0.0));
  if (behind) { radius = 0.0; }

  var inst: Instance;
  let zc = clamp(ndc.z, 0.0, 1.0);
  if (behind) {
    inst.clip_pos = vec4<f32>(2.0, 2.0, 1.0, 1.0); // off-screen; radius=0 also kills it
    inst.cov      = vec4<f32>(1.0, 0.0, 1.0, 0.0);
  } else {
    inst.clip_pos = vec4<f32>(ndc.xy, zc, clip.w);
    inst.cov      = vec4<f32>(c00, c01, c11, radius);
  }
  inst.color = vec4<f32>(s.color.rgb, opacity);
  p_inst[i] = inst;

  // Sort key: bigger view-space depth = drawn first (back-to-front). We bit-
  // pack a u32 from the float. To get correct ascending order over both
  // signs of f32 IEEE-754 reinterpret + a fix-up flip is required, but here
  // we sort positive depths only — behind-camera splats get depth=0 and are
  // suppressed by radius=0 anyway.
  let dpos = max(depth, 0.0);
  // We want back-to-front => largest depth FIRST. Radix sort below sorts
  // ascending, so we invert: key = 0xFFFFFFFF - bitcast(d) gives descending
  // semantics. NaN-safe because dpos is clamped.
  let kd = bitcast<u32>(dpos);
  p_keys[i] = 0xffffffffu - kd;
  p_indices[i] = i;
}
`;

export const RADIX_SORT_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// WebGPU radix sort over u32 keys, carrying a u32 payload (the splat index).
//
// Algorithm: classic 4-bit (16-bin) LSD radix sort. Each 32-bit key is sorted
// in 8 sequential passes. Each pass consists of three kernels:
//
//   1. cs_histogram  — per-workgroup local histogram, written out to
//                      \`histograms[workgroup * 16 + bin]\`. WG_SIZE = 256.
//   2. cs_scan       — single-workgroup exclusive prefix sum over the entire
//                      histogram array (length numWorkgroups * 16).
//   3. cs_scatter    — read scanned offsets, scatter each (key, index) pair
//                      into its bucket position.
//
// Inspired by:
//   - Wyman, "wgsl-radix-sort" (github.com/cwyman/wgsl-radix-sort) — overall
//     three-pass split radix structure.
//   - Merrill & Grimshaw 2010, "High Performance and Scalable Radix Sorting".
//   - antimatter15 / splatviz GPU sort prototypes (multi-pass LSD on u32).
//
// We deliberately avoid storage-buffer atomics: each workgroup writes its own
// histogram slot, the scan runs in a single workgroup using shared memory,
// and the scatter uses a per-workgroup local prefix scan to compute intra-
// workgroup destination offsets without atomicAdd. Atomics on storage buffers
// are still optional in WebGPU 1.0 and not on the mandatory feature set.

const WG_SIZE : u32 = 256u;
const RADIX   : u32 = 16u;       // 4-bit radix → 16 bins per pass.
const PASSES  : u32 = 8u;        // 32 bits / 4 bits

struct Uniforms {
  count: u32,
  bit_shift: u32,    // 0, 4, 8, ..., 28
  num_wgs: u32,      // ceil(count / WG_SIZE)
  _pad: u32,
};

@group(0) @binding(0) var<storage, read>       keys_in    : array<u32>;
@group(0) @binding(1) var<storage, read>       values_in  : array<u32>;
@group(0) @binding(2) var<storage, read_write> keys_out   : array<u32>;
@group(0) @binding(3) var<storage, read_write> values_out : array<u32>;
@group(0) @binding(4) var<storage, read_write> histograms : array<u32>;
@group(0) @binding(5) var<uniform>             u : Uniforms;

// Workgroup-shared per-bin counters.
var<workgroup> wg_hist : array<atomic<u32>, RADIX>;
// Workgroup-shared offsets table used in the scatter pass.
var<workgroup> wg_offsets : array<u32, RADIX>;
// Workgroup-shared scan scratch (single-workgroup scan over per-thread totals).
var<workgroup> scan_scratch : array<u32, WG_SIZE>;

// ---------------------------------------------------------------------------
// Pass 1: histogram. One workgroup of 256 threads handles 256 keys; each
// thread atomically increments the bucket for its key. The atomics here are
// *workgroup*-scoped — WebGPU mandates \`atomic<u32>\` in \`var<workgroup>\`.
// (Storage-buffer atomics are NOT used anywhere.)
// ---------------------------------------------------------------------------
@compute @workgroup_size(WG_SIZE)
fn cs_histogram(
  @builtin(global_invocation_id)  gid : vec3<u32>,
  @builtin(local_invocation_id)   lid : vec3<u32>,
  @builtin(workgroup_id)          wgid : vec3<u32>,
) {
  if (lid.x < RADIX) {
    atomicStore(&wg_hist[lid.x], 0u);
  }
  workgroupBarrier();

  let i = gid.x;
  if (i < u.count) {
    let k = keys_in[i];
    let bin = (k >> u.bit_shift) & 0xfu;
    atomicAdd(&wg_hist[bin], 1u);
  }
  workgroupBarrier();

  // Thread 0..15 writes the workgroup's 16 bins to the global histogram
  // table at slot [bin * num_wgs + wgid]. This bin-major layout means the
  // global exclusive scan naturally places all of bin 0's workgroups first,
  // then bin 1's, etc. — i.e. ascending sort order without an extra grouping
  // pass after the scan.
  if (lid.x < RADIX) {
    let h = atomicLoad(&wg_hist[lid.x]);
    histograms[lid.x * u.num_wgs + wgid.x] = h;
  }
}

// ---------------------------------------------------------------------------
// Pass 2: exclusive prefix-sum over the entire histogram array. This shader
// runs as a single workgroup (256 threads) and uses a Blelloch up-down sweep
// in workgroup-shared memory. It assumes num_wgs * RADIX <= 4096
// (i.e. up to 256 dispatched histogram workgroups = 65,536 elements per
// pass — sufficient for 10M+ splats since the histogram pass uses
// 256-key tiles ⇒ num_wgs = 10M/256 ≈ 39062 wgs, which exceeds 256).
//
// For large num_wgs (>256), we chunk the scan: each thread strides through
// \`num_wgs * RADIX / WG_SIZE\` elements doing a serial accumulate first, then
// performs a workgroup-wide scan over the per-thread totals, and finally a
// per-thread serial add-back. Sequential adjacent-difference is fine because
// the scan only needs to run *once* per radix pass.
//
// In practice the layout we use is: thread i owns elements
// histograms[i], histograms[i + WG_SIZE], histograms[i + 2*WG_SIZE], ...
// ---------------------------------------------------------------------------
@compute @workgroup_size(WG_SIZE)
fn cs_scan(@builtin(local_invocation_id) lid : vec3<u32>) {
  let total = u.num_wgs * RADIX;
  // Step 1: each thread sums its strided slice.
  var tsum: u32 = 0u;
  var idx: u32 = lid.x;
  loop {
    if (idx >= total) { break; }
    tsum = tsum + histograms[idx];
    idx = idx + WG_SIZE;
  }
  scan_scratch[lid.x] = tsum;
  workgroupBarrier();

  // Step 2: in-shared exclusive scan over WG_SIZE entries. Hillis-Steele.
  for (var offset: u32 = 1u; offset < WG_SIZE; offset = offset << 1u) {
    var v: u32 = 0u;
    if (lid.x >= offset) {
      v = scan_scratch[lid.x - offset];
    }
    workgroupBarrier();
    scan_scratch[lid.x] = scan_scratch[lid.x] + v;
    workgroupBarrier();
  }
  // Convert inclusive → exclusive scan.
  let prefix_total = scan_scratch[lid.x];
  let my_block_exclusive = prefix_total - tsum;
  workgroupBarrier();

  // Step 3: walk strided slice again, writing exclusive prefix.
  var running: u32 = my_block_exclusive;
  var idx2: u32 = lid.x;
  loop {
    if (idx2 >= total) { break; }
    let v = histograms[idx2];
    histograms[idx2] = running;
    running = running + v;
    idx2 = idx2 + WG_SIZE;
  }
}

// ---------------------------------------------------------------------------
// Pass 3: scatter. Each workgroup recomputes its local histogram (cheaper
// than persisting per-element bin assignments to a side buffer), then derives
// each element's destination index as:
//
//   dst[i] = histograms[wgid * RADIX + bin_of(i)]   (global exclusive prefix)
//          + local_position_of(i, bin_of(i))
//
// We compute \`local_position_of\` by re-scanning bins inside the workgroup:
// thread 0 of each bin atomically adds, then we use the returned old value
// as the local rank. Order within a bin is the natural intra-workgroup
// dispatch order — which is deterministic given a fixed global-id pattern.
// ---------------------------------------------------------------------------
@compute @workgroup_size(WG_SIZE)
fn cs_scatter(
  @builtin(global_invocation_id) gid : vec3<u32>,
  @builtin(local_invocation_id)  lid : vec3<u32>,
  @builtin(workgroup_id)         wgid: vec3<u32>,
) {
  // Init per-bin local counters to 0. Read the global exclusive offset for
  // this (bin, workgroup) pair from the bin-major scanned histogram.
  if (lid.x < RADIX) {
    atomicStore(&wg_hist[lid.x], 0u);
    wg_offsets[lid.x] = histograms[lid.x * u.num_wgs + wgid.x];
  }
  workgroupBarrier();

  let i = gid.x;
  var bin: u32 = 0u;
  var key: u32 = 0u;
  var val: u32 = 0u;
  var local_rank: u32 = 0u;
  var live: bool = false;
  if (i < u.count) {
    key = keys_in[i];
    val = values_in[i];
    bin = (key >> u.bit_shift) & 0xfu;
    // atomicAdd returns the old value → that's the rank of this element
    // within its bin for this workgroup.
    local_rank = atomicAdd(&wg_hist[bin], 1u);
    live = true;
  }
  workgroupBarrier();

  if (live) {
    let dst = wg_offsets[bin] + local_rank;
    keys_out[dst]   = key;
    values_out[dst] = val;
  }
}
`;

export const SCAN_MULTIBLOCK_WGSL: string = `// SPDX-License-Identifier: Apache-2.0
//
// Multi-block exclusive prefix-sum (3-kernel chained scan).
//
// Replaces the single-workgroup \`cs_scan\` step inside the radix sort. The
// original implementation had a single workgroup of 256 threads stride
// through the entire histogram array (\`num_wgs * RADIX\` elements). For
// 10 M splats that's ~625 K elements scanned by 256 threads, eight times
// per sort — the dominant cost in the sort.
//
// This file implements the classic chained scan from Merrill & Grimshaw 2010
// using zero storage-buffer atomics (we don't have them mandatory in
// WebGPU 1.0). Three kernels per scan:
//
//   1. cs_scan_per_wg          — each workgroup of \`WG_SIZE\` threads does an
//                                exclusive scan over its tile, writes the
//                                scan back in-place, and writes the tile
//                                total to \`block_sums[wgid]\`.
//   2. cs_scan_block_sums      — a single workgroup does an exclusive scan
//                                over the \`block_sums\` array. For up to
//                                \`2 * WG_SIZE * WG_SIZE\` = 131 072 tiles
//                                (which is 33 M-element tiles' worth of
//                                block sums; far more than we ever need
//                                — 10 M splats yield ~2 442 tiles) the
//                                single-WG scan with serial striding is
//                                trivial and not the bottleneck.
//   3. cs_scan_add_block_sums  — each workgroup adds its scanned
//                                \`block_sums[wgid]\` to every element in its
//                                tile, producing the final global exclusive
//                                prefix.
//
// We intentionally keep the bind-group layout identical to the existing
// radix-sort layout (binding 4 = histograms / data, binding 5 = uniforms),
// but add a sixth binding for \`block_sums\`. The radix-sort orchestration
// rebinds for these kernels because the meaning of bindings 0..3 differs.
//
// Inspired by:
//   - Merrill & Grimshaw 2010, "Parallel Scan for Stream Architectures".
//   - Harris et al., "Parallel Prefix Sum (Scan) with CUDA", GPU Gems 3.
//   - Wyman, "wgsl-radix-sort", for the WGSL idiom (workgroup-shared
//     Hillis-Steele).

const WG_SIZE : u32 = 256u;

struct ScanUniforms {
  total:        u32,   // total elements to scan == num_wgs_radix * RADIX
  num_scan_wgs: u32,   // ceil(total / WG_SIZE)
  _pad0:        u32,
  _pad1:        u32,
};

@group(0) @binding(0) var<storage, read_write> data       : array<u32>;
@group(0) @binding(1) var<storage, read_write> block_sums : array<u32>;
@group(0) @binding(2) var<uniform>             us         : ScanUniforms;

// Workgroup-shared scan scratch.
var<workgroup> ss_scratch : array<u32, WG_SIZE>;

// ---------------------------------------------------------------------------
// Phase A: per-workgroup exclusive scan over a \`WG_SIZE\` tile.
//
// Each workgroup loads its tile into shared memory, performs a Hillis-Steele
// scan (inclusive → exclusive), writes the exclusive prefix back to \`data\`,
// and stores the tile total in \`block_sums[wgid]\`.
// ---------------------------------------------------------------------------
@compute @workgroup_size(WG_SIZE)
fn cs_scan_per_wg(
  @builtin(global_invocation_id) gid  : vec3<u32>,
  @builtin(local_invocation_id)  lid  : vec3<u32>,
  @builtin(workgroup_id)         wgid : vec3<u32>,
) {
  let i = gid.x;
  var v: u32 = 0u;
  if (i < us.total) {
    v = data[i];
  }
  ss_scratch[lid.x] = v;
  workgroupBarrier();

  // Hillis-Steele inclusive scan over WG_SIZE entries.
  for (var offset: u32 = 1u; offset < WG_SIZE; offset = offset << 1u) {
    var add: u32 = 0u;
    if (lid.x >= offset) {
      add = ss_scratch[lid.x - offset];
    }
    workgroupBarrier();
    ss_scratch[lid.x] = ss_scratch[lid.x] + add;
    workgroupBarrier();
  }

  // Inclusive[lid] - original[lid] = exclusive[lid].
  let inclusive = ss_scratch[lid.x];
  let exclusive = inclusive - v;
  if (i < us.total) {
    data[i] = exclusive;
  }

  // Last live thread in this tile writes the block total.
  // For a fully-populated tile this is lid.x == WG_SIZE - 1.
  // For the tail tile (i >= us.total beyond some point) we still want the
  // last-loaded element's inclusive prefix, which is the tile's total over
  // the valid prefix only (v was zero for OOB lanes).
  if (lid.x == WG_SIZE - 1u) {
    block_sums[wgid.x] = inclusive;
  }
}

// ---------------------------------------------------------------------------
// Phase B: single-workgroup exclusive scan over \`block_sums\`.
//
// \`num_scan_wgs\` is small (≤ a few thousand for 10 M splats per pass), so a
// single workgroup of WG_SIZE threads striding through the array is fine.
// This kernel mirrors the original \`cs_scan\` body but operates on
// \`block_sums\` instead of \`histograms\`.
// ---------------------------------------------------------------------------
@compute @workgroup_size(WG_SIZE)
fn cs_scan_block_sums(@builtin(local_invocation_id) lid : vec3<u32>) {
  let total = us.num_scan_wgs;
  // Step 1: each thread sums its strided slice.
  var tsum: u32 = 0u;
  var idx: u32 = lid.x;
  loop {
    if (idx >= total) { break; }
    tsum = tsum + block_sums[idx];
    idx = idx + WG_SIZE;
  }
  ss_scratch[lid.x] = tsum;
  workgroupBarrier();

  // Step 2: shared exclusive scan over WG_SIZE per-thread totals.
  for (var offset: u32 = 1u; offset < WG_SIZE; offset = offset << 1u) {
    var v: u32 = 0u;
    if (lid.x >= offset) {
      v = ss_scratch[lid.x - offset];
    }
    workgroupBarrier();
    ss_scratch[lid.x] = ss_scratch[lid.x] + v;
    workgroupBarrier();
  }
  let prefix_total = ss_scratch[lid.x];
  let my_block_exclusive = prefix_total - tsum;
  workgroupBarrier();

  // Step 3: re-walk slice, writing the exclusive prefix back.
  var running: u32 = my_block_exclusive;
  var idx2: u32 = lid.x;
  loop {
    if (idx2 >= total) { break; }
    let v = block_sums[idx2];
    block_sums[idx2] = running;
    running = running + v;
    idx2 = idx2 + WG_SIZE;
  }
}

// ---------------------------------------------------------------------------
// Phase C: each workgroup adds its exclusive \`block_sums[wgid]\` to every
// element of its tile, producing the global exclusive prefix sum.
// ---------------------------------------------------------------------------
@compute @workgroup_size(WG_SIZE)
fn cs_scan_add_block_sums(
  @builtin(global_invocation_id) gid  : vec3<u32>,
  @builtin(workgroup_id)         wgid : vec3<u32>,
) {
  let i = gid.x;
  if (i >= us.total) { return; }
  let bias = block_sums[wgid.x];
  data[i] = data[i] + bias;
}
`;
