// iOSDemoApp — the minimum a real app needs to render a splat with the SDK.
//
// The bundled `synth.glb` (10k synthetic splats, ~550 KB) is generated by
// `cargo run --example gen_synth_glb` and ships with the demo so the app
// shows something out of the box without external downloads. For a real
// 3DGS scene drop `bonsai-7k.glb` (or any other KHR_gaussian_splatting `.glb`)
// into `Sources/iOSDemo/Assets/` and the loader picks it up automatically.

import SwiftUI
import CatetusViewer

@main
struct iOSDemoApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

struct ContentView: View {
    var body: some View {
        // Prefer a real bonsai-7k.glb if the user dropped one in; otherwise
        // fall back to the bundled synthetic fixture so the demo always shows
        // something splat-shaped on first launch.
        if let url = Bundle.module.url(forResource: "bonsai-7k", withExtension: "glb") {
            CatetusViewer(assetURL: url).ignoresSafeArea()
        } else if let url = Bundle.module.url(forResource: "synth", withExtension: "glb") {
            CatetusViewer(assetURL: url).ignoresSafeArea()
        } else {
            Text("No .glb bundled — run `cargo run --example gen_synth_glb`")
                .padding()
        }
    }
}
